const fs = require('fs');
const wordsPath = 'E:/Tina/自研背单词软件/words.json';
const words = JSON.parse(fs.readFileSync(wordsPath, 'utf-8'));

// Complete phonetic dictionary for the 153 missing words
const phoneticMap = {
  'aloud': '[əˈlaʊd]',
  'always': '[ˈɔːlweɪz]',
  'am': '[æm]',
  'american': '[əˈmerɪkən]',
  'anybody': '[ˈenibɒdi]',
  'are': '[ɑː(r)]',
  'asia': '[ˈeɪʒə]',
  'at': '[ət]',
  'attend': '[əˈtend]',
  'attention': '[əˈtenʃn]',
  'awake': '[əˈweɪk]',
  'awful': '[ˈɔːfl]',
  'behavior': '[bɪˈheɪvjə(r)]',
  'birth': '[bɜːθ]',
  'cost': '[kɒst]',
  'country': '[ˈkʌntri]',
  'courage': '[ˈkʌrɪdʒ]',
  'dance': '[dɑːns]',
  'danger': '[ˈdeɪndʒə(r)]',
  'dark': '[dɑːk]',
  'decide': '[dɪˈsaɪd]',
  'deep': '[diːp]',
  'dictionary': '[ˈdɪkʃənri]',
  'difficult': '[ˈdɪfɪkəlt]',
  'direct': '[dəˈrekt]',
  'dish': '[dɪʃ]',
  'divide': '[dɪˈvaɪd]',
  'doctor': '[ˈdɒktə(r)]',
  'doubt': '[daʊt]',
  'dream': '[driːm]',
  'drink': '[drɪŋk]',
  'drum': '[drʌm]',
  'education': '[ˌedʒuˈkeɪʃn]',
  'effort': '[ˈefət]',
  'eight': '[eɪt]',
  'eleven': '[ɪˈlevn]',
  'else': '[els]',
  'energy': '[ˈenədʒi]',
  'englishwoman': '[ˈɪŋɡlɪʃwʊmən]',
  'enter': '[ˈentə(r)]',
  'especially': '[ɪˈspeʃəli]',
  'ever': '[ˈevə(r)]',
  'every': '[ˈevri]',
  'example': '[ɪɡˈzɑːmpl]',
  'excite': '[ɪkˈsaɪt]',
  'expect': '[ɪkˈspekt]',
  'fact': '[fækt]',
  'fair': '[feə(r)]',
  'fall': '[fɔːl]',
  'family': '[ˈfæməli]',
  'fantastic': '[fænˈtæstɪk]',
  'fight': '[faɪt]',
  'find': '[faɪnd]',
  'fish': '[fɪʃ]',
  'five': '[faɪv]',
  'foot': '[fʊt]',
  'football': '[ˈfʊtbɔːl]',
  'foreign': '[ˈfɒrən]',
  'four': '[fɔː(r)]',
  'free': '[friː]',
  'from': '[frəm]',
  'german': '[ˈdʒɜːmən]',
  'give': '[ɡɪv]',
  'grandchild': '[ˈɡræntʃaɪld]',
  'grandparent': '[ˈɡrænpeərənt]',
  'guitar': '[ɡɪˈtɑː(r)]',
  'habit': '[ˈhæbɪt]',
  'hate': '[heɪt]',
  'he': '[hiː]',
  'head': '[hed]',
  'her': '[hɜː(r)]',
  'hero': '[ˈhɪərəʊ]',
  'hundred': '[ˈhʌndrəd]',
  'hungry': '[ˈhʌŋɡri]',
  'i': '[aɪ]',
  'idea': '[aɪˈdɪə]',
  'ill': '[ɪl]',
  'improvement': '[ɪmˈpruːvmənt]',
  'interview': '[ˈɪntəvjuː]',
  'invent': '[ɪnˈvent]',
  'it': '[ɪt]',
  'japan': '[dʒəˈpæn]',
  'kill': '[kɪl]',
  'kilo': '[ˈkiːləʊ]',
  'land': '[lænd]',
  'last': '[lɑːst]',
  'law': '[lɔː]',
  'leaf': '[liːf]',
  'left': '[left]',
  'letter': '[ˈletə(r)]',
  'level': '[ˈlevl]',
  'library': '[ˈlaɪbrəri]',
  'line': '[laɪn]',
  'list': '[lɪst]',
  'live': '[lɪv]',
  'look': '[lʊk]',
  'lose': '[luːz]',
  'love': '[lʌv]',
  'luck': '[lʌk]',
  'maybe': '[ˈmeɪbi]',
  'middle': '[ˈmɪdl]',
  'money': '[ˈmʌni]',
  'near': '[nɪə(r)]',
  'neck': '[nek]',
  'need': '[niːd]',
  'neighbor': '[ˈneɪbə(r)]',
  'next': '[nekst]',
  'nine': '[naɪn]',
  'noise': '[nɔɪz]',
  'noon': '[nuːn]',
  'north': '[nɔːθ]',
  'office': '[ˈɒfɪs]',
  'on': '[ɒn]',
  'or': '[ɔː(r)]',
  'over': '[ˈəʊvə(r)]',
  'paint': '[peɪnt]',
  'pardon': '[ˈpɑːdn]',
  'part': '[pɑːt]',
  'pass': '[pɑːs]',
  'patient': '[ˈpeɪʃnt]',
  'perhaps': '[pəˈhæps]',
  'please': '[pliːz]',
  'police': '[pəˈliːs]',
  'polite': '[pəˈlaɪt]',
  'pond': '[pɒnd]',
  'population': '[ˌpɒpjuˈleɪʃn]',
  'pride': '[praɪd]',
  'punish': '[ˈpʌnɪʃ]',
  'rapid': '[ˈræpɪd]',
  'regard': '[rɪˈɡɑːd]',
  'regret': '[rɪˈɡret]',
  'russia': '[ˈrʌʃə]',
  'satisfy': '[ˈsætɪsfaɪ]',
  'separate': '[ˈseprət]',
  'seven': '[ˈsevn]',
  'silence': '[ˈsaɪləns]',
  'similar': '[ˈsɪmələ(r)]',
  'six': '[sɪks]',
  'space': '[speɪs]',
  'spirit': ['ˈspɪrɪt]'],
  'stomach': '[ˈstʌmək]',
  'sudden': '[ˈsʌdn]',
  'themselves': '[ðəmˈselvz]',
  'they': '[ðeɪ]',
  'though': '[ðəʊ]',
  'thousand': '[ˈθaʊznd]',
  'three': '[θriː]',
  'tiny': '[ˈtaɪni]',
  'treat': '[triːt]',
  'twelve': '[twelv]',
  'uncomfortable': '[ʌnˈkʌmftəbl]',
  'worth': '[wɜːθ]',
  'you': '[juː]',
  'africa': '[ˈæfrɪkə]',
  'afford': '[əˈfɔːd]',
  'adult': '[ˈædʌlt]',
  'advise': '[ədˈvaɪz]',
  'alarm': '[əˈlɑːm]',
};

let fixedCount = 0;
const fixedWords = words.map(w => {
  if (!w.phonetic || w.phonetic === '') {
    const ph = phoneticMap[w.word.toLowerCase()];
    if (ph) {
      fixedCount++;
      return { ...w, phonetic: ph };
    }
  }
  return w;
});

console.log('Phonetics fixed:', fixedCount);

// Still missing?
const stillMissing = fixedWords.filter(w => !w.phonetic || w.phonetic === '');
console.log('Still missing phonetics:', stillMissing.length);
if (stillMissing.length) {
  stillMissing.forEach(w => console.log('  -', w.word));
}

fs.writeFileSync(wordsPath, JSON.stringify(fixedWords, null, 2), 'utf-8');
console.log('Saved!');
