const fs = require('fs');
const path = 'E:\\Tina\\自研背单词软件\\words.json';
const data = JSON.parse(fs.readFileSync(path, 'utf-8'));

// 为795个空搭配词生成合理搭配
const collocationMap = {
  // A
  8: ['be accurate in sth', 'accurate information'],
  9: ['have a headache', 'ache for sth'],
  15: ['a famous actor', 'an actor playing Hamlet'],
  16: ['a young actress', 'an actress from China'],
  17: ['actually happen', 'actually speaking'],
  23: ['an adventure story', 'have an adventure'],
  24: ['put an advertisement', 'advertisement for sth'],
  27: ['affect sb deeply', 'be affected by sth'],
  30: ['Africa', 'in Africa'],
  36: ['an aged man', 'aged 10'],
  37: ['long ago', 'a while ago'],
  41: ['fresh air', 'by air', 'on air'],
  42: ['airline ticket', 'domestic airline'],
  43: ['at the airport', 'airport terminal'],
  51: ['already done', 'already known'],
  53: ['although though', 'even although'],
  56: ['A.M.', '8 a.m.'],
  58: ['have ambition', 'ambition for sth'],
  59: ['America', 'in America'],
  60: ['American culture', 'an American'],
  61: ['among them', 'among the best'],
  64: ['amusing story', 'amusing game'],
  66: ['and so on', 'you and I'],
  67: ['angrily shout', 'leave angrily'],
  69: ['wild animal', 'animal protection'],
  72: ['any more', 'any time'],
  73: ['anybody else', 'if anybody'],
  74: ['anything else', 'do anything'],
  75: ['go anywhere', 'anywhere near'],
  76: ['apologize to sb', 'apologize for sth'],
  77: ['appear in public', 'appear to be'],
  80: ['in April', 'April Fools\' Day'],
  83: ['arm in arm', 'take sb in one\'s arms'],
  84: ['join the army', 'army life'],
  90: ['an article about', 'write an article'],
  91: ['a famous artist', 'artist of the year'],
  93: ['in Asia', 'Asia Pacific'],
  97: ['attack sb', 'under attack', 'heart attack'],
  98: ['attend a meeting', 'attend school'],
  100: ['attitude to/toward sth', 'positive attitude'],
  102: ['attractive to sb', 'attractive price'],
  103: ['audience of', 'large audience'],
  104: ['in August', 'August holiday'],
  105: ['my aunt', 'aunt and uncle'],
  107: ['Australian English', 'an Australian'],
  // B
  116: ['baby boy', 'have a baby'],
  118: ['background information', 'educational background'],
  120: ['shopping bag', 'a bag of'],
  121: ['bakery shop', 'at the bakery'],
  125: ['a bunch of bananas', 'banana tree'],
  127: ['a bar of chocolate', 'bar counter', 'snack bar'],
  129: ['basic skills', 'basic need'],
  130: ['shopping basket', 'a basket of'],
  133: ['go to the bathroom', 'bathroom break'],
  134: ['battery dead', 'charge the battery'],
  138: ['a bear hug', 'bear in mind'],
  141: ['sing beautifully', 'beautifully done'],
  142: ['beauty contest', 'natural beauty'],
  146: ['in the bedroom', 'bedroom window'],
  147: ['beef noodle', 'beef steak'],
  151: ['at the beginning of', 'from beginning to end'],
  152: ['good behaviour', 'behaviour problem'],
  156: ['ring the bell', 'bell rings'],
  160: ['beside the point', 'beside the bed'],
  161: ['besides English', 'besides that'],
  168: ['rubbish bin', 'bin bag'],
  169: ['a bird in the hand', 'kill two birds with one stone'],
  170: ['happy birthday', 'birthday party', 'birthday cake'],
  171: ['a packet of biscuits', 'chocolate biscuit'],
  173: ['bite into', 'take a bite'],
  174: ['black and white', 'black coffee', 'in black'],
  176: ['a warm blanket', 'blanket coverage'],
  178: ['block the way', 'a block of', 'traffic block'],
  179: ['blood pressure', 'blood test'],
  181: ['light blue', 'blue sky', 'feel blue'],
  183: ['by boat', 'boat trip', 'row a boat'],
  185: ['boil water', 'boiling point', 'boiled egg'],
  197: ['boy friend', 'a boy of ten'],
  198: ['brain damage', 'use one\'s brain', 'brainstorm'],
  204: ['breathe in/out', 'breathe deeply', 'out of breath'],
  205: ['cross the bridge', 'bridge over', 'burn bridges'],
  208: ['in Britain', 'Britain and France'],
  209: ['British English', 'the British'],
  210: ['a Briton', 'ancient Britons'],
  213: ['brown hair', 'brown sugar', 'light brown'],
  217: ['the Bund', 'on the Bund'],
  221: ['businessman and entrepreneur', 'a successful businessman'],
  224: ['butter and bread', 'butter knife'],
  225: ['butterfly effect', 'catch butterflies'],
  // C
  230: ['cabbage soup', 'Chinese cabbage'],
  231: ['café bar', 'at the café'],
  232: ['a piece of cake', 'birthday cake', 'make a cake'],
  235: ['digital camera', 'camera phone'],
  238: ['in Canada', 'Canada and the US'],
  239: ['Canadian English', 'a Canadian'],
  242: ['team captain', 'captain of the team'],
  244: ['ID card', 'credit card', 'birthday card'],
  247: ['listen carefully', 'do sth carefully'],
  248: ['careless mistake', 'careless driver'],
  249: ['grated carrot', 'carrot juice'],
  250: ['carry on', 'carry out', 'carry a bag'],
  251: ['cartoon character', 'watch cartoons'],
  253: ['a black cat', 'let the cat out'],
  256: ['cave in', 'explore a cave'],
  257: ['celebrate sth', 'celebrate Christmas'],
  261: ['certainly not', 'certainly will'],
  262: ['a chain of', 'chain store', 'food chain'],
  263: ['sit on a chair', 'take the chair'],
  264: ['face a challenge', 'challenge sb to do sth'],
  267: ['changeable weather', 'changeable mind'],
  268: ['TV channel', 'English Channel'],
  271: ['charity event', 'charity work', 'in charity'],
  273: ['cheap price', 'dirt cheap', 'cheap labor'],
  276: ['cheese cake', 'a piece of cheese'],
  278: ['chemistry class', 'chemistry lab'],
  282: ['a child of', 'childhood friend', 'only child'],
  283: ['in one\'s childhood', 'childhood memory'],
  286: ['Chinese food', 'Chinese New Year', 'in Chinese'],
  287: ['chocolate bar', 'a box of chocolates'],
  290: ['use chopsticks', 'a pair of chopsticks'],
  294: ['draw a circle', 'in a circle', 'circle around'],
  296: ['big city', 'city center', 'city life'],
  298: ['my classmate', 'old classmate'],
  299: ['in the classroom', 'clean the classroom'],
  302: ['see clearly', 'clearly stated'],
  303: ['bank clerk', 'shop clerk'],
  305: ['click on', 'double click', 'right click'],
  307: ['at the clinic', 'health clinic'],
  308: ['alarm clock', 'set the clock', 'round the clock'],
  311: ['a cloud of', 'cloud nine', 'under a cloud'],
  312: ['cloudy day', 'cloudy sky'],
  314: ['coat hanger', 'winter coat', 'take off one\'s coat'],
  315: ['a cup of coffee', 'coffee shop', 'black coffee'],
  316: ['a coin', 'toss a coin', 'gold coin'],
  321: ['colour TV', 'what colour', 'change colour'],
  329: ['competition for', 'in competition with', 'fierce competition'],
  331: ['complete the form', 'complete with', 'a complete set'],
  332: ['completely different', 'completely sure'],
  336: ['press conference', 'attend a conference'],
  338: ['confident about', 'confident in', 'be confident'],
  344: ['work out a problem', 'work out at the gym'],
  345: ['speech contest', 'win a contest'],
  348: ['convenient for', 'convenient time', 'convenient store'],
  350: ['cook a meal', 'cook dinner', 'a good cook'],
  355: ['answer correctly', 'do sth correctly'],
  357: ['cotton shirt', 'cotton candy', 'cotton field'],
  360: ['developing country', 'across the country', 'country music'],
  365: ['crazy about', 'go crazy', 'drive sb crazy'],
  366: ['ice cream', 'cream cheese', 'face cream'],
  // D
  367: ['dance to music', 'dance class', 'dance floor'],
  368: ['in danger', 'out of danger', 'danger zone'],
  370: ['dark blue', 'in the dark', 'after dark'],
  371: ['social date', 'date back to', 'out of date'],
  373: ['daughter of', 'son and daughter'],
  376: ['customer service', 'regular customer'],
  378: ['a day off', 'every day', 'one day'],
  379: ['dead or alive', 'dead end', 'dead line'],
  381: ['dear friend', 'dear Sir/Madam'],
  383: ['in December', 'December holiday'],
  386: ['make a decision', 'decision making'],
  387: ['deep breath', 'deep in thought', 'deep blue'],
  389: ['defeat sb', 'suffer a defeat'],
  390: ['defend oneself', 'defend against'],
  391: ['a delicious meal', 'delicious food'],
  393: ['a good deal', 'deal with', 'a great deal of'],
  394: ['December', 'in December'],
  395: ['make a decision', 'decide to do sth'],
  396: ['deep breath', 'deep voice'],
  397: ['defeat the enemy', 'suffer defeat'],
  398: ['defend one\'s country', 'defend sb from'],
  // E
  402: ['early bird', 'early morning', 'as early as'],
  403: ['earn money', 'earn a living', 'earn respect'],
  404: ['take it easy', 'easier said than done'],
  405: ['eat up', 'eat out', 'eat healthy'],
  408: ['economic development', 'economic growth'],
  409: ['educational system', 'educational background'],
  410: ['effective way', 'effective measure'],
  411: ['effort to', 'make an effort', 'spare no effort'],
  413: ['either...or', 'on either side'],
  414: ['elder brother', 'elder sister'],
  415: ['be elected', 'election campaign'],
  416: ['electric fan', 'electric power', 'electric car'],
  417: ['electronic product', 'electronic mail'],
  418: ['elementary school', 'elementary education'],
  419: ['elephant tusk', 'see an elephant'],
  420: ['elevator button', 'take the elevator'],
  421: ['dialogue between', 'have a dialogue'],
  423: ['end up', 'in the end', 'at the end of'],
  425: ['enjoy doing', 'enjoy oneself'],
  426: ['enjoyable trip', 'enjoyable experience'],
  427: ['enough time', 'more than enough', 'good enough'],
  428: ['enter the room', 'enter for'],
  429: ['entire life', 'entire family'],
  430: ['dig up', 'dig a hole', 'dig out'],
  432: ['dining hall', 'dining room', 'dining table'],
  433: ['dinner party', 'have dinner', 'dinner time'],
  435: ['direct flight', 'direct result'],
  436: ['change direction', 'in the direction of'],
  437: ['director of', 'film director'],
  439: ['discover sth', 'discover that'],
  441: ['discuss sth with sb', 'under discussion'],
  443: ['dish washer', 'a dish of', 'main dish'],
  445: ['display window', 'on display'],
  446: ['distance learning', 'in the distance', 'keep distance'],
  447: ['do homework', 'do business', 'do one\'s best'],
  449: ['a doctor of', 'see a doctor', 'doctor\'s degree'],
  450: ['keep a diary', 'write in one\'s diary'],
  452: ['dictionary definition', 'look up in a dictionary'],
  455: ['a healthy diet', 'on a diet', 'diet food'],
  456: ['differ from', 'different from'],
  458: ['difficult to', 'have difficulty (in) doing'],
  460: ['dig a hole', 'dig out', 'dig into'],
  462: ['digital camera', 'digital age'],
  463: ['dining hall', 'dining room'],
  465: ['direct answer', 'direct flight'],
  466: ['in the direction of', 'change direction'],
  467: ['film director', 'director general'],
  468: ['dirty water', 'dirty hands', 'play dirty'],
  470: ['on duty', 'off duty', 'sense of duty'],
  471: ['each other', 'each of'],
  472: ['eager to', 'eager for'],
  473: ['eagle eye', 'bald eagle'],
  475: ['early bird', 'in the early morning'],
  476: ['earn a living', 'earn money'],
  477: ['earthquake hit', 'on earth', 'down to earth'],
  478: ['easily done', 'more easily'],
  479: ['east of', 'in the east', 'Middle East'],
  480: ['easy going', 'take it easy', 'easier said than done'],
  481: ['eat out', 'eat up', 'eat away'],
  482: ['ecology', 'ecological balance'],
  483: ['edge of', 'on the edge'],
  486: ['effort to do', 'make an effort', 'no effort'],
  487: ['either side', 'either way'],
  488: ['elder people', 'respect elders'],
  489: ['be elected as', 'presidential election'],
  490: ['electricity bill', 'cut off electricity'],
  491: ['electronic dictionary', 'electronic product'],
  492: ['elementary school', 'elementary level'],
  493: ['elephant trunk', 'African elephant'],
  494: ['something else', 'or else', 'nothing else'],
  495: ['e-mail address', 'send an e-mail'],
  496: ['emergency exit', 'in an emergency', 'emergency room'],
  497: ['emergency call', 'state of emergency'],
  498: ['emotional support', 'emotion control'],
  499: ['employ sb', 'employer and employee'],
  500: ['encourage sb to do', 'be encouraged by'],
  501: ['in the end', 'end up', 'put an end to'],
  502: ['enemy of', 'make enemies'],
  503: ['energy saving', 'full of energy', 'energy drink'],
  504: ['engage in', 'be engaged to'],
  505: ['English class', 'spoken English', 'in English'],
  506: ['enjoy doing', 'enjoy life'],
  507: ['enjoyable weekend', 'enjoyable trip'],
  508: ['enough for', 'not enough'],
  509: ['enter for', 'enter the room'],
  510: ['entertainment industry', 'live entertainment'],
  511: ['enthusiastic about', 'show enthusiasm'],
  512: ['entire day', 'entire family'],
  513: ['entrance exam', 'at the entrance'],
  514: ['envelope', 'in the envelope'],
  515: ['environment protection', 'environment friendly'],
  516: ['especially for', 'especially when'],
  517: ['evening dress', 'in the evening', 'evening news'],
  518: ['event organizer', 'sporting event'],
  519: ['ever since', 'for ever', 'hardly ever'],
  520: ['every day', 'every other', 'every time'],
  521: ['everybody else', 'almost everybody'],
  522: ['everyday life', 'everyday use'],
  523: ['everyone knows', 'everyone else'],
  524: ['everything else', 'do everything'],
  525: ['everywhere in', 'almost everywhere'],
  526: ['evidence for', 'scientific evidence'],
  527: ['evil spirit', 'the evil'],
  // F
  528: ['exact time', 'exact number', 'to be exact'],
  529: ['examination results', 'medical examination', 'take an exam'],
  530: ['for example', 'set an example', 'example of'],
  531: ['excellent at', 'excellent result'],
  532: ['except for', 'except that'],
  533: ['exciting news', 'exciting game'],
  534: ['excuse me', 'find an excuse', 'make an excuse'],
  535: ['do exercise', 'take exercise', 'morning exercise'],
  536: ['exhibition hall', 'art exhibition', 'on exhibition'],
  537: ['exist in', 'exist on'],
  538: ['exit from', 'emergency exit'],
  539: ['expand business', 'expand to'],
  540: ['expect to', 'expect sth of sb', 'as expected'],
  541: ['expensive gift', 'too expensive'],
  542: ['experience of', 'gain experience'],
  543: ['an experiment on', 'do an experiment'],
  544: ['expert at/in', 'an expert on'],
  545: ['explain sth to sb', 'explanation for'],
  546: ['explore the world', 'explore possibilities'],
  548: ['express oneself', 'express train', 'facial expression'],
  549: ['extra work', 'extra time', 'no extra charge'],
  550: ['extreme sport', 'go to extremes'],
  551: ['eye contact', 'keep an eye on', 'catch one\'s eye'],
  552: ['eyesight', 'good eyesight', 'poor eyesight'],
  553: ['face to face', 'face the challenge', 'save face', 'lose face'],
  554: ['fact is', 'in fact', 'as a matter of fact'],
  555: ['factory worker', 'factory building'],
  556: ['fail to', 'fail in', 'fail the exam'],
  557: ['failure in', 'end in failure'],
  558: ['fair play', 'fair price', 'it\'s fair to say'],
  559: ['fall asleep', 'fall behind', 'fall in love with'],
  560: ['false alarm', 'true or false'],
  561: ['be familiar with', 'be familiar to'],
  562: ['famous for', 'famous as', 'make sb famous'],
  563: ['far away', 'far from', 'so far', 'as far as'],
  564: ['farm house', 'on the farm', 'farm worker'],
  565: ['fast food', 'fast train', 'as fast as'],
  566: ['fat free', 'get fat', 'fat chance'],
  567: ['father and son', 'father figure'],
  568: ['fault line', 'my fault', 'find fault with'],
  569: ['favour of', 'do sb a favour', 'in favour of'],
  570: ['favourite food', 'my favourite', 'favourite subject'],
  571: ['fear of', 'in fear', 'for fear that'],
  572: ['February', 'in February', 'February 14th'],
  573: ['feed on', 'feed back', 'be fed up with'],
  574: ['feel like', 'feel free', 'feel sorry for'],
  575: ['a few', 'few of', 'only a few'],
  576: ['field trip', 'in the field', 'track and field'],
  577: ['fight against', 'fight for', 'fight back'],
  578: ['fill in', 'fill out', 'be filled with'],
  579: ['film star', 'see a film', 'film maker'],
  580: ['final exam', 'in the final', 'final decision'],
  581: ['find out', 'find it hard to', 'find one\'s way'],
  582: ['by ferry', 'ferry boat', 'take a ferry'],
  583: ['feverish', 'have a fever', 'run a fever'],
  584: ['a few', 'quite a few', 'few of them'],
  585: ['field trip', 'in the field of'],
  586: ['fight back', 'fight for one\'s rights'],
  587: ['figure out', 'figure of speech'],
  588: ['fill in the blank', 'fill up', 'be filled with'],
  589: ['final result', 'final exam'],
  590: ['find out', 'find sb doing sth'],
  591: ['fine weather', 'fine art', 'that\'s fine'],
  592: ['finger print', 'point a finger', 'cross one\'s fingers'],
  593: ['finish line', 'finish doing', 'from start to finish'],
  594: ['fire alarm', 'catch fire', 'on fire', 'make a fire'],
  595: ['first of all', 'at first', 'first aid', 'first name'],
  596: ['fish and chips', 'go fishing', 'fish tank'],
  597: ['fit in', 'fit for', 'keep fit'],
  598: ['a five-star hotel', 'five years old'],
  599: ['fix up', 'fix the problem', 'in a fix'],
  600: ['flash light', 'in a flash', 'flash back'],
  601: ['flat tire', 'flat screen', 'fall flat'],
  602: ['a flight to', 'flight number', 'catch a flight'],
  603: ['floor plan', 'ground floor', 'first floor'],
  604: ['flour and water', 'flour mill'],
  605: ['flow chart', 'flow of traffic', 'cash flow'],
  606: ['a bunch of flowers', 'flower shop'],
  607: ['flu virus', 'catch the flu', 'bird flu'],
  608: ['flush the toilet', 'flush of red'],
  609: ['focus on', 'out of focus', 'in focus'],
  610: ['fold up', 'fold one\'s arms'],
  611: ['follow sb', 'as follows', 'follow the rules'],
  612: ['fond of', 'be fond of doing'],
  613: ['fool around', 'make a fool of', 'April Fool\'s'],
  614: ['foot ball', 'on foot', 'at the foot of'],
  615: ['for example', 'for instance', 'for sure', 'for good'],
  616: ['forbid sb to do', 'forbidden area'],
  617: ['force sb to do', 'by force', 'in force'],
  618: ['forecast weather', 'weather forecast'],
  619: ['foreign country', 'foreign language', 'foreigner'],
  620: ['foresee the future', 'foresee problems'],
  621: ['forest fire', 'in the forest', 'rainforest'],
  622: ['forget about', 'forget to do', 'never forget'],
  623: ['forgive sb for', 'forgive and forget'],
  624: ['form a habit', 'in the form of', 'application form'],
  625: ['former president', 'the former...the latter'],
  627: ['fortunate to', 'be fortunate in'],
  628: ['fortunately for', 'fortunately enough'],
  629: ['forward to', 'look forward to', 'bring forward'],
  630: ['found on', 'be founded in', 'found a company'],
  631: ['fountain pen', 'fountain of youth'],
  632: ['fox hole', 'as cunning as a fox'],
  633: ['fragile item', 'fragile glass'],
  634: ['free of charge', 'feel free', 'free time', 'set free'],
  635: ['freedom of speech', 'freedom from'],
  636: ['freeze to death', 'freezing point', 'freeze over'],
  637: ['fresh air', 'fresh water', 'fresh food', 'freshman'],
  638: ['Friday', 'on Friday', 'Black Friday'],
  639: ['fridge door', 'in the fridge'],
  640: ['friendship between', 'make friends with', 'best friend'],
  641: ['frighten sb', 'be frightened of', 'frightened to death'],
  642: ['from now on', 'from time to time', 'from scratch'],
  643: ['front of', 'in front of', 'in the front of'],
  644: ['fruit juice', 'bear fruit', 'fresh fruit'],
  645: ['fry pan', 'stir fry', 'deep fry'],
  646: ['full of', 'in full', 'full name', 'full time'],
  647: ['have fun', 'funny story', 'make fun of'],
  648: ['furniture store', 'a piece of furniture'],
  649: ['further study', 'further information', 'nothing further'],
  650: ['future plan', 'in the future', 'in future'],
  // G
  651: ['gain weight', 'gain knowledge', 'gain experience'],
  652: ['game over', 'Olympic Games', 'play games'],
  653: ['garbage can', 'garbage truck', 'take out the garbage'],
  654: ['garden party', 'in the garden', 'garden city'],
  655: ['gas station', 'gas mask', 'natural gas'],
  656: ['gateway to', 'default gateway'],
  657: ['general manager', 'in general', 'general public'],
  658: ['generation gap', 'from generation to generation'],
  659: ['generous to', 'be generous with', 'it\'s generous of sb'],
  660: ['gentle man', 'gentle touch', 'ladies and gentlemen'],
  661: ['geography class', 'physical geography'],
  662: ['German car', 'in German'],
  663: ['Germany', 'in Germany'],
  664: ['get up', 'get on', 'get off', 'get rid of'],
  665: ['gift shop', 'birthday gift', 'a gift for'],
  666: ['giraffe', 'see a giraffe'],
  667: ['girl friend', 'a little girl'],
  668: ['give up', 'give in', 'give away', 'give back'],
  669: ['glad to', 'be glad about', 'glad to hear'],
  670: ['glass of water', 'glass window', 'a piece of glass'],
  671: ['global warming', 'global market'],
  672: ['glove box', 'a pair of gloves', 'take off gloves'],
  673: ['glue stick', 'glue to', 'super glue'],
  674: ['go ahead', 'go on', 'go through', 'let go'],
  675: ['goal keeper', 'achieve a goal', 'set a goal'],
  676: ['gold medal', 'gold mine', 'golden age'],
  677: ['golden chance', 'golden hair'],
  678: ['good at', 'good for', 'as good as', 'very good'],
  679: ['goodbye to', 'say goodbye', 'kiss goodbye'],
  680: ['grade A', 'in Grade One', 'get good grades'],
  681: ['graduation ceremony', 'after graduation'],
  682: ['grand child', 'grand parents'],
  683: ['granddaughter', 'grandson and granddaughter'],
  684: ['grandfather clock', 'my grandfather'],
  685: ['grandmother', 'my grandmother'],
  686: ['grandson', 'a grandson of'],
  687: ['grape vine', 'a bunch of grapes', 'grape juice'],
  688: ['grass land', 'on the grass', 'green grass'],
  689: ['great deal', 'a great many', 'great importance'],
  690: ['green tea', 'green house', 'go green'],
  691: ['greet sb', 'greet with a smile'],
  692: ['ground floor', 'on the ground', 'play ground'],
  693: ['group work', 'a group of', 'in groups'],
  694: ['grow up', 'grow into', 'grow out of'],
  695: ['guard against', 'under guard', 'off guard'],
  696: ['guess what', 'make a guess', 'wild guess'],
  697: ['tour guide', 'guide sb to'],
  698: ['guitar player', 'play the guitar', 'acoustic guitar'],
  // H
  700: ['habit of', 'form a habit', 'break the habit'],
  701: ['hair cut', 'hair style', 'have one\'s hair cut'],
  702: ['hairdresser\'s', 'go to the hairdresser'],
  703: ['half of', 'in half', 'half an hour'],
  704: ['hall of fame', 'concert hall', 'dining hall'],
  705: ['hamburger', 'eat a hamburger'],
  706: ['hand in', 'hand out', 'on the one hand', 'give a hand'],
  707: ['handbag', 'designer handbag'],
  708: ['handsome boy', 'handsome reward'],
  709: ['handwriting', 'handwriting on the wall'],
  710: ['hang on', 'hang up', 'hang out with'],
  711: ['happen to', 'happen to do', 'as it happens'],
  712: ['happy birthday', 'happy about', 'happy to do'],
  713: ['hard work', 'work hard', 'hardly ever'],
  714: ['hardly...when', 'hardly anyone'],
  715: ['harmful to', 'do harm to', 'no harm done'],
  716: ['hat and coat', 'wear a hat', 'take off one\'s hat'],
  717: ['hate doing', 'hate to do'],
  718: ['have to', 'have got to', 'had better'],
  719: ['he who', 'he himself'],
  720: ['head for', 'head of', 'use one\'s head'],
  721: ['headache', 'have a headache'],
  722: ['headmaster', 'school headmaster'],
  723: ['health care', 'in good health', 'health food'],
  724: ['hear from', 'hear of', 'hear about'],
  725: ['heart attack', 'by heart', 'lose heart', 'break one\'s heart'],
  726: ['heat wave', 'heat up', 'in the heat'],
  727: ['heavy rain', 'heavy traffic', 'heavy box'],
  728: ['height of', 'in height'],
  729: ['hello to', 'say hello', 'hello there'],
  730: ['help sb with', 'help oneself to', 'with the help of'],
  731: ['helpful to', 'be helpful for'],
  732: ['hen house', 'a hen laying eggs'],
  733: ['her book', 'of her own'],
  734: ['here and there', 'here we go', 'be here'],
  735: ['hero of', 'national hero'],
  736: ['herself', 'by herself', 'for herself'],
  737: ['hey there', 'hey presto'],
  738: ['hi everyone', 'say hi to'],
  739: ['hide and seek', 'hide from', 'hide sth from sb'],
  740: ['high school', 'high quality', 'jump high'],
  741: ['hiking trip', 'go hiking', 'hiking boots'],
  742: ['hill side', 'on top of the hill', 'over the hill'],
  743: ['himself', 'by himself', 'for himself'],
  744: ['hire sb', 'for hire', 'hire a car'],
  745: ['his own', 'of his'],
  746: ['history of', 'in history', 'make history'],
  747: ['hit on', 'hit the target', 'a big hit'],
  748: ['hobby group', 'hobby and interest'],
  749: ['hold on', 'hold back', 'hold a meeting', 'catch hold of'],
  750: ['hole in', 'a hole in one'],
  751: ['holiday season', 'on holiday', 'summer holiday', 'public holiday'],
  752: ['home town', 'go home', 'at home', 'homesick'],
  753: ['homework', 'do homework', 'hand in homework'],
  754: ['honest with', 'to be honest', 'honestly speaking'],
  755: ['honey moon', 'honey bee'],
  756: ['Hong Kong', 'from Hong Kong'],
  757: ['hope for', 'hope to do', 'in the hope of'],
  758: ['horse riding', 'on horse back', 'dark horse'],
  759: ['hospital bed', 'in hospital', 'out of hospital', 'go to hospital'],
  760: ['hot dog', 'hot spring', 'too hot'],
  761: ['hotel room', 'stay at a hotel', 'five-star hotel'],
  762: ['hour and a half', 'per hour', 'rush hour'],
  763: ['house work', 'house wife', 'move house'],
  764: ['how about', 'how come', 'how far', 'how long'],
  765: ['however', 'no matter how'],
  766: ['huge success', 'a huge amount of'],
  767: ['human being', 'human rights', 'human nature'],
  768: ['hundred of', 'hundreds of', 'one hundred'],
  769: ['hungry for', 'go hungry', 'feel hungry'],
  770: ['hunt for', 'go hunting', 'hunt down'],
  771: ['hurry up', 'in a hurry', 'no hurry'],
  772: ['hurt oneself', 'get hurt', 'feel hurt'],
  // I
  773: ['ice cream', 'ice cube', 'on thin ice'],
  774: ['idea about', 'have an idea', 'good idea'],
  775: ['if only', 'as if', 'even if', 'if so'],
  776: ['ill in bed', 'fall ill', 'mentally ill'],
  777: ['illness', 'suffer from illness', 'serious illness'],
  778: ['imagine doing', 'imagine that', 'use one\'s imagination'],
  779: ['immediate action', 'immediate family', 'immediately after'],
  780: ['importance of', 'of great importance', 'attach importance to'],
  781: ['important to', 'it is important that', 'play an important role'],
  782: ['impossible to', 'next to impossible', 'it\'s impossible'],
  783: ['improve in', 'improve one\'s English', 'improve the situation'],
  784: ['in other words', 'in a word', 'in all', 'in fact'],
  785: ['inch by inch', 'every inch'],
  786: ['include sth', 'included in', 'including but not limited to'],
  787: ['increase by', 'on the increase', 'increase to'],
  788: ['indeed', 'very much indeed'],
  789: ['independent of', 'be independent from'],
  790: ['indicate that', 'indication of'],
  791: ['indoor activity', 'indoor swimming pool'],
  792: ['industrial area', 'industrial revolution'],
  793: ['industry', 'service industry', 'IT industry'],
  794: ['infect with', 'be infected by'],
  795: ['influence on', 'under the influence of', 'have influence over'],
  796: ['inform sb of', 'keep sb informed'],
  797: ['information about', 'a piece of information', 'for your information'],
  798: ['ingredient for', 'active ingredient'],
  799: ['initial stage', 'in the initial phase'],
  800: ['injure sb', 'be injured', 'the injured'],
  801: ['ink pen', 'in ink'],
  802: ['inn', 'country inn'],
  803: ['inner world', 'inner city'],
  804: ['inside out', 'inside the box'],
  805: ['insist on', 'insist that'],
  806: ['inspire sb to do', 'draw inspiration from'],
  807: ['install sth', 'installation guide'],
  808: ['instead of', 'instead'],
  809: ['institute of', 'research institute'],
  810: ['instruction manual', 'follow instructions', 'instruct sb to do'],
  811: ['instrument', 'musical instrument', 'play an instrument'],
  812: ['insurance', 'insurance company', 'life insurance'],
  813: ['intellectual property', 'intellectual curiosity'],
  814: ['intelligence', 'artificial intelligence', 'IQ test'],
  815: ['intend to', 'be intended for', 'intention to'],
  816: ['interest in', 'with interest', 'lose interest in'],
  817: ['interesting book', 'an interesting story'],
  818: ['interfere with', 'interference in'],
  819: ['internal affairs', 'internal medicine'],
  820: ['international', 'international trade', 'international student'],
  821: ['internet', 'on the Internet', 'Internet access'],
  822: ['interpret as', 'simultaneous interpretation'],
  823: ['interrupt sb', 'don\'t interrupt', 'interruption to'],
  824: ['interval', 'at intervals', 'during the interval'],
  825: ['interview for', 'job interview', 'have an interview'],
  826: ['into the room', 'get into', 'look into'],
  827: ['introduce sb to', 'introduction to'],
  828: ['invent sth', 'invention of', 'inventor of'],
  829: ['invest in', 'investment in', 'return on investment'],
  830: ['invite sb to', 'invitation to', 'you\'re invited'],
  831: ['involve in', 'be involved in', 'involvement in'],
  832: ['iron shirt', 'iron out', 'strike while the iron is hot'],
  833: ['island', 'on the island', 'desert island'],
  834: ['issue of', 'issue a statement', 'make an issue of'],
  835: ['itself', 'by itself', 'in itself'],
  // J
  836: ['jacket pocket', 'life jacket', 'wear a jacket'],
  837: ['January', 'in January', 'January 1st'],
  838: ['jar of', 'a jar of jam', 'cookie jar'],
  839: ['jazz music', 'jazz club'],
  840: ['jeans and T-shirt', 'a pair of jeans'],
  841: ['jeep', 'drive a jeep'],
  842: ['jet lag', 'jet plane'],
  843: ['jewelry store', 'wear jewelry'],
  844: ['job market', 'apply for a job', 'lose one\'s job', 'do a good job'],
  845: ['jog in the park', 'go jogging'],
  846: ['join in', 'join the army', 'join the club'],
  847: ['joke about', 'play a joke on', 'make a joke', 'practical joke'],
  848: ['journal of', 'keep a journal', 'academic journal'],
  849: ['journey to', 'have a good journey', 'safe journey'],
  850: ['joy of', 'with joy', 'full of joy'],
  851: ['judge by', 'judging from', 'pass judgment on'],
  852: ['juice bar', 'a glass of juice', 'orange juice'],
  853: ['July', 'in July', 'July 4th'],
  854: ['jump to', 'jump over', 'jump at', 'high jump'],
  855: ['June', 'in June', 'June 1st'],
  856: ['junior high', 'junior to'],
  857: ['just now', 'just then', 'just in time', 'just so-so'],
  // K
  858: ['keep on', 'keep up with', 'keep in touch', 'keep fit'],
  859: ['key to', 'car key', 'turn the key'],
  860: ['keyboard', 'type on the keyboard', 'keyboard player'],
  861: ['kick off', 'kick the ball', 'free kick'],
  862: ['kid around', 'just kidding'],
  863: ['kill time', 'kill two birds', 'kill sb with kindness'],
  864: ['kilo of', 'half a kilo', 'a kilo of apples'],
  865: ['kind of', 'a kind of', 'all kinds of', 'be kind to'],
  866: ['king of', 'kingdom', 'lion king'],
  867: ['kiss goodbye', 'blow a kiss', 'kiss of life'],
  868: ['kitchen table', 'in the kitchen', 'kitchen ware'],
  869: ['kite flying', 'fly a kite', 'go fly a kite'],
  870: ['knee', 'on one\'s knees', 'knee injury'],
  871: ['knife and fork', 'sharp knife', 'a knife in the back'],
  872: ['knock at', 'knock on', 'knock down', 'knock over'],
  873: ['know about', 'know sth by heart', 'as far as I know'],
  874: ['knowledge of', 'to my knowledge', 'common knowledge'],
  // L
  875: ['lab report', 'in the lab', 'language lab'],
  876: ['label on', 'read the label', 'brand label'],
  877: ['labor market', 'physical labor', 'labor union'],
  878: ['lack of', 'for lack of', 'lack in'],
  879: ['ladder', 'climb the ladder', 'social ladder'],
  880: ['lady first', 'lady and gentleman', 'ladies\' room'],
  881: ['lake', 'by the lake', 'on the lake', 'lake side'],
  882: ['lamp post', 'turn on the lamp', 'table lamp'],
  883: ['land on', 'land use', 'farmland', 'motherland'],
  884: ['language', 'first language', 'foreign language', 'body language'],
  885: ['large amount', 'at large', 'by and large'],
  886: ['last but not least', 'at last', 'last name', 'last year'],
  887: ['late for', 'be late', 'better late than never', 'of late'],
  888: ['laugh at', 'laugh out loud', 'have a good laugh'],
  889: ['launch a product', 'launch pad'],
  890: ['laundry room', 'do the laundry'],
  891: ['law and order', 'break the law', 'pass a law', 'by law'],
  892: ['lawn mower', 'on the lawn'],
  893: ['lawyer', 'hire a lawyer', 'defense lawyer'],
  894: ['lay the table', 'lay off', 'lay out', 'lay emphasis on'],
  895: ['lazy bones', 'too lazy to'],
  896: ['lead to', 'take the lead', 'lead sb to do', 'in the lead'],
  897: ['leaf', 'turn over a new leaf', 'green leaves'],
  898: ['lean against', 'lean on', 'lean meat'],
  899: ['learn from', 'learn by heart', 'learn about'],
  900: ['least of all', 'at least', 'not in the least'],
  901: ['leave alone', 'leave behind', 'leave for', 'on leave'],
  902: ['lecture on', 'give a lecture', 'attend a lecture'],
  903: ['left and right', 'on the left', 'turn left'],
  904: ['leg', 'on one\'s last legs', 'leg pain'],
  905: ['legal advice', 'legal age', 'it\'s legal'],
  906: ['lemon juice', 'lemon tree', 'bitter lemon'],
  907: ['lend sth to sb', 'lend a hand'],
  908: ['length of', 'at length', 'in length'],
  909: ['less than', 'more or less', 'none the less'],
  910: ['lesson plan', 'have a lesson', 'give sb a lesson'],
  911: ['let down', 'let go', 'let me see', 'let alone'],
  912: ['letter box', 'write a letter', 'by letter', 'capital letter'],
  913: ['level of', 'on the level', 'sea level'],
  914: ['library card', 'in the library', 'borrow from the library'],
  915: ['license plate', 'driver\'s license', 'business license'],
  916: ['lie down', 'lie in', 'lie about', 'tell a lie'],
  917: ['life style', 'way of life', 'daily life', 'come to life'],
  918: ['lift up', 'give sb a lift', 'take the lift'],
  919: ['light bulb', 'turn on the light', 'traffic light', 'green light'],
  920: ['like doing', 'feel like', 'would like to', 'if you like'],
  921: ['likely to', 'most likely', 'not likely'],
  922: ['limit to', 'time limit', 'speed limit', 'within limits'],
  923: ['line up', 'in line with', 'on the line', 'hold the line'],
  924: ['link to', 'be linked with', 'a link between'],
  925: ['lion', 'lion king', 'as brave as a lion'],
  926: ['lip stick', 'on one\'s lips', 'read my lips'],
  927: ['list of', 'on the list', 'make a list', 'waiting list'],
  928: ['listen to', 'listen carefully', 'listen for'],
  929: ['literature', 'English literature', 'classical literature'],
  930: ['litter bin', 'no littering', 'drop litter'],
  931: ['little by little', 'a little', 'quite a little'],
  932: ['live in', 'live on', 'live up to', 'make a living'],
  933: ['load of', 'a load of', 'take a load off'],
  934: ['local time', 'local people', 'local government'],
  935: ['lock the door', 'under lock and key', 'lock up'],
  936: ['log in', 'log out', 'log on'],
  937: ['London', 'in London', 'London Bridge'],
  938: ['lonely', 'feel lonely', 'lonely planet'],
  939: ['long for', 'as long as', 'before long', 'no longer'],
  940: ['look at', 'look for', 'look after', 'look up', 'look forward to'],
  941: ['lose weight', 'lose face', 'lose one\'s temper', 'lose heart'],
  942: ['a lot of', 'lots of', 'a lot'],
  943: ['loud noise', 'loud speaker', 'read aloud'],
  944: ['love at first sight', 'fall in love', 'would love to'],
  945: ['low price', 'low temperature', 'feel low'],
  946: ['luck', 'good luck', 'bad luck', 'in luck', 'out of luck'],
  947: ['lucky dog', 'lucky enough', 'strike lucky'],
  948: ['lunch time', 'have lunch', 'business lunch'],
  949: ['lung cancer', 'lung disease'],
  // M
  950: ['machine gun', 'vending machine', 'washing machine'],
  951: ['mad about', 'go mad', 'mad at', 'drive sb mad'],
  952: ['magazine', 'read a magazine', 'monthly magazine'],
  953: ['magic show', 'as if by magic', 'black magic'],
  954: ['mail box', 'send a mail', 'by mail', 'e-mail'],
  955: ['main street', 'main reason', 'in the main'],
  956: ['major in', 'major problem', 'majority of'],
  957: ['make up', 'make sure', 'make sense', 'make a difference'],
  958: ['male and female', 'male teacher'],
  959: ['mall', 'shopping mall', 'go to the mall'],
  960: ['man and wife', 'manage to', 'manage a company'],
  961: ['many of', 'a good many', 'how many'],
  962: ['map of', 'on the map', 'road map'],
  963: ['March', 'in March', 'March 8th'],
  964: ['mark down', 'full marks', 'get good marks'],
  965: ['market', 'stock market', 'market share', 'flea market'],
  966: ['marry sb', 'get married', 'be married to'],
  967: ['master degree', 'master of', 'master piece'],
  968: ['match box', 'football match', 'match...with'],
  969: ['math problem', 'do math', 'math class'],
  970: ['matter of fact', 'what\'s the matter', 'no matter'],
  971: ['May', 'in May', 'May Day'],
  972: ['maybe', 'maybe not', 'just maybe'],
  973: ['me too', 'excuse me', 'as for me'],
  974: ['meal time', 'have a meal', 'cook a meal'],
  975: ['mean to', 'mean business', 'what do you mean'],
  976: ['meaning of', 'meaningful life', 'mean well'],
  977: ['meat ball', 'red meat', 'fresh meat'],
  978: ['medical care', 'medical check', 'medical team'],
  979: ['medicine for', 'take medicine', 'traditional medicine'],
  980: ['meet the need', 'meet with', 'sports meet'],
  981: ['meeting room', 'have a meeting', 'attend a meeting'],
  982: ['melt down', 'melt away', 'melting point'],
  983: ['member of', 'team member', 'family member'],
  984: ['memory of', 'in memory of', 'from memory'],
  985: ['mend clothes', 'on the mend'],
  986: ['mental health', 'mental illness', 'make up one\'s mind'],
  987: ['mention that', 'don\'t mention it', 'not to mention'],
  988: ['menu card', 'on the menu'],
  989: ['merely', 'not merely...but also'],
  990: ['merry Christmas', 'merry go round'],
  991: ['message board', 'leave a message', 'take a message', 'text message'],
  992: ['metal', 'heavy metal', 'metal detector'],
  993: ['method of', 'teaching method', 'scientific method'],
  994: ['middle school', 'in the middle of', 'middle class'],
  995: ['might as well', 'with all one\'s might'],
  996: ['milk shake', 'a glass of milk', 'powdered milk'],
  997: ['mind your own business', 'make up one\'s mind', 'change one\'s mind'],
  998: ['mine', 'of mine', 'a friend of mine'],
  999: ['mineral water', 'mineral resource', 'vitamins and minerals'],
  1000: ['minister of', 'prime minister'],
  1001: ['minute hand', 'in a minute', 'wait a minute', 'last minute'],
  1002: ['mirror', 'look in the mirror', 'mirror image'],
  1003: ['miss the bus', 'miss sb', 'missing person'],
  1004: ['mistake for', 'by mistake', 'make a mistake'],
  1005: ['mix up', 'mix with', 'a mix of'],
  1006: ['mobile phone', 'mobile', 'on mobile'],
  1007: ['model car', 'role model', 'fashion model'],
  1008: ['modern art', 'modern times', 'modern history'],
  1009: ['mom and dad', 'stay with mom'],
  1010: ['Monday', 'on Monday', 'Monday morning'],
  1011: ['money', 'make money', 'save money', 'spend money on'],
  1012: ['monitor', 'class monitor', 'computer monitor'],
  1013: ['monkey', 'make a monkey of', 'monkey business'],
  1014: ['month', 'last month', 'next month', 'month by month'],
  1015: ['mood', 'in a good mood', 'bad mood', 'moody'],
  1016: ['moon cake', 'full moon', 'on the moon', 'moon light'],
  1017: ['moral', 'moral standard', 'moral support'],
  1018: ['more or less', 'more than', 'the more...the more'],
  1019: ['morning paper', 'in the morning', 'from morning till night'],
  1020: ['most of', 'at most', 'make the most of'],
  1021: ['mother tongue', 'mother land', 'step mother'],
  1022: ['motor bike', 'motor way', 'motor cycle'],
  1023: ['mountain', 'mountain climbing', 'mountain top', 'move mountains'],
  1024: ['mouse pad', 'computer mouse', 'as quiet as a mouse'],
  1025: ['mouth', 'keep one\'s mouth shut', 'by word of mouth'],
  1026: ['move on', 'move to', 'move house', 'on the move'],
  1027: ['movie star', 'go to the movies', 'movie theater'],
  1028: ['much more', 'too much', 'not much', 'as much as'],
  1029: ['museum', 'history museum', 'art museum', 'visit a museum'],
  1030: ['music', 'listen to music', 'pop music', 'classical music'],
  1031: ['must be', 'must have done', 'if you must'],
  1032: ['myself', 'by myself', 'for myself', 'to myself'],
  // N
  1033: ['nail', 'finger nail', 'hit the nail on the head'],
  1034: ['name after', 'in the name of', 'full name', 'family name'],
  1035: ['narrow down', 'narrow escape', 'a narrow road'],
  1036: ['nation wide', 'the Chinese nation', 'United Nations'],
  1037: ['national flag', 'national day', 'national park'],
  1038: ['native language', 'native speaker', 'be native to'],
  1039: ['natural', 'natural disaster', 'natural beauty', 'come naturally'],
  1040: ['nature', 'in nature', 'by nature', 'second nature'],
  1041: ['near by', 'near to', 'come near'],
  1042: ['nearly', 'not nearly', 'nearly there'],
  1043: ['necessary for', 'if necessary', 'it\'s necessary that'],
  1044: ['neck', 'neck tie', 'around the neck', 'neck and neck'],
  1045: ['need for', 'in need of', 'meet the need'],
  1046: ['needle', 'as sharp as a needle', 'thread a needle'],
  1047: ['negative', 'negative effect', 'negative attitude'],
  1048: ['neither...nor', 'neither of', 'me neither'],
  1049: ['nephew', 'my nephew'],
  1050: ['nervous about', 'feel nervous', 'nervous system'],
  1051: ['net work', 'on the net', 'net weight', 'safety net'],
  1052: ['never mind', 'never before', 'better late than never'],
  1053: ['new year', 'Happy New Year', 'brand new'],
  1054: ['news report', 'good news', 'bad news', 'on the news'],
  1055: ['newspaper', 'read a newspaper', 'in the newspaper'],
  1056: ['next to', 'next door', 'the next day', 'next time'],
  1057: ['nice to', 'nice to meet you', 'nice and warm'],
  1058: ['niece', 'my niece'],
  1059: ['night', 'at night', 'good night', 'midnight', 'over night'],
  1060: ['nine out of ten', 'nine to five'],
  1061: ['no one', 'no more', 'no longer', 'no wonder'],
  1062: ['nobody', 'nobody else', 'nobody knows'],
  1063: ['nod one\'s head', 'nod off', 'nod in agreement'],
  1064: ['noise', 'make a noise', 'too much noise', 'noise pollution'],
  1065: ['none of', 'none other than', 'second to none'],
  1066: ['noodle soup', 'rice noodle', 'instant noodle'],
  1067: ['noon', 'at noon', 'by noon', 'high noon'],
  1068: ['nor', 'neither...nor', 'nor do I'],
  1069: ['normal', 'back to normal', 'above normal', 'normal temperature'],
  1070: ['north of', 'in the north', 'North America'],
  1071: ['nose', 'runny nose', 'as plain as the nose on your face'],
  1072: ['note down', 'take notes', 'leave a note'],
  1073: ['nothing but', 'nothing else', 'for nothing', 'have nothing to do'],
  1074: ['notice board', 'take notice of', 'without notice'],
  1075: ['November', 'in November', 'November 11th'],
  1076: ['now and then', 'by now', 'from now on', 'just now'],
  1077: ['nowhere', 'get nowhere', 'out of nowhere'],
  1078: ['nuclear', 'nuclear energy', 'nuclear weapon', 'nuclear family'],
  1079: ['number', 'a number of', 'the number of', 'phone number'],
  1080: ['nurse', 'see a nurse', 'nursing home', 'school nurse'],
  1081: ['nut', 'a tough nut to crack', 'peanut', 'cashew nut'],
  // O
  1082: ['obey the rules', 'obey orders'],
  1083: ['object to', 'an object of', 'take objection to'],
  1084: ['observe sth', 'observe that'],
  1085: ['obvious', 'it\'s obvious that', 'obviously'],
  1086: ['occasion', 'on occasion', 'special occasion', 'on the occasion of'],
  1087: ['occupy', 'be occupied with', 'occupation'],
  1088: ['occur to', 'it occurred to me that'],
  1089: ['ocean', 'in the ocean', 'Pacific Ocean', 'ocean view'],
  1090: ['o\'clock', 'at 3 o\'clock'],
  1091: ['October', 'in October', 'October 1st'],
  1092: ['of course', 'because of', 'instead of', 'a lot of'],
  1093: ['off duty', 'off work', 'day off', 'take off'],
  1094: ['offer to', 'offer sb sth', 'turn down an offer'],
  1095: ['office', 'office building', 'post office', 'head office'],
  1096: ['officer', 'police officer', 'army officer'],
  1097: ['official', 'government official', 'official language'],
  1098: ['often', 'very often', 'how often', 'as often as'],
  1099: ['oh', 'oh my god', 'oh dear'],
  1100: ['oil', 'cooking oil', 'oil painting', 'olive oil'],
  1101: ['OK', 'that\'s OK', 'OK then'],
  1102: ['old', 'how old', 'old friend', 'old days'],
  1103: ['on time', 'on duty', 'and so on', 'later on'],
  1104: ['once', 'at once', 'once upon a time', 'once more'],
  1105: ['one by one', 'one of', 'for one thing'],
  1106: ['oneself', 'by oneself', 'for oneself'],
  1107: ['online', 'go online', 'online shopping', 'online game'],
  1108: ['only', 'not only...but also', 'if only', 'only just'],
  1109: ['onto', 'get onto', 'jump onto'],
  1110: ['open up', 'open the door', 'in the open', 'opening hours'],
  1111: ['operate on', 'operate a machine', 'operation room'],
  1112: ['opinion', 'in one\'s opinion', 'public opinion', 'have a good opinion of'],
  1113: ['opportunity', 'have the opportunity to', 'job opportunity', 'equal opportunity'],
  1114: ['opposite', 'opposite to', 'on the opposite side'],
  1115: ['or', 'or else', 'or so', 'either...or'],
  1116: ['orange', 'orange juice', 'orange tree', 'sque