const fs = require('fs');
const path = 'E:\\Tina\\自研背单词软件\\words.json';
const data = JSON.parse(fs.readFileSync(path, 'utf-8'));

// 高质量搭配映射表 - 基于词义和常见用法
const collMap = {
  8: ['be accurate in sth', 'accurate information'],
  9: ['have a headache', 'ache for sth'],
  15: ['a famous actor', 'an actor playing a role'],
  16: ['a young actress', 'an actress from China'],
  17: ['actually happen', 'actually speaking'],
  23: ['an adventure story', 'have an adventure'],
  24: ['put an advertisement', 'advertisement for sth'],
  27: ['affect sb deeply', 'be affected by sth'],
  30: ['in Africa', 'Africa continent'],
  36: ['an aged man', 'aged 10'],
  37: ['long ago', 'a while ago'],
  41: ['fresh air', 'by air', 'on air'],
  42: ['airline ticket', 'domestic airline'],
  43: ['at the airport', 'airport terminal'],
  51: ['already done', 'already known'],
  53: ['although though', 'even although'],
  56: ['8 a.m.', 'in the morning'],
  58: ['have ambition', 'ambition for sth'],
  59: ['in America', 'America and Europe'],
  60: ['American culture', 'an American'],
  61: ['among them', 'among the best'],
  64: ['amusing story', 'amusing game'],
  66: ['and so on', 'you and I'],
  67: ['shout angrily', 'leave angrily'],
  69: ['wild animal', 'animal protection'],
  72: ['any more', 'any time'],
  73: ['anybody else', 'if anybody'],
  74: ['anything else', 'do anything'],
  75: ['go anywhere', 'anywhere near'],
  76: ['apologize to sb', 'apologize for sth'],
  77: ['appear in public', 'appear to be'],
  80: ['in April', "April Fools' Day"],
  83: ['arm in arm', 'take sb in one\'s arms'],
  84: ['join the army', 'army life'],
  90: ['an article about', 'write an article'],
  91: ['a famous artist', 'artist of the year'],
  93: ['in Asia', 'Asia Pacific'],
  97: ['attack sb', 'under attack', 'heart attack'],
  98: ['attend a meeting', 'attend school'],
  100: ['attitude to/toward sth', 'positive attitude'],
  102: ['attractive to sb', 'attractive price'],
  103: ['audience of', 'large audience'],
  104: ['in August', 'August holiday'],
  105: ['my aunt', 'aunt and uncle'],
  107: ['Australian English', 'an Australian'],
  116: ['baby boy', 'have a baby'],
  118: ['background information', 'educational background'],
  120: ['shopping bag', 'a bag of'],
  121: ['at the bakery', 'bakery shop'],
  125: ['a bunch of bananas', 'banana tree'],
  127: ['a bar of chocolate', 'snack bar', 'bar counter'],
  129: ['basic skills', 'basic need'],
  130: ['shopping basket', 'a basket of'],
  133: ['go to the bathroom', 'bathroom break'],
  134: ['battery dead', 'charge the battery'],
  138: ['a bear hug', 'bear in mind'],
  141: ['sing beautifully', 'beautifully done'],
  142: ['beauty contest', 'natural beauty'],
  146: ['in the bedroom', 'bedroom window'],
  147: ['beef noodle', 'beef steak'],
  151: ['at the beginning of', 'from beginning to end'],
  152: ['good behaviour', 'behaviour problem'],
  156: ['ring the bell', 'bell rings'],
  160: ['beside the point', 'beside the bed'],
  161: ['besides English', 'besides that'],
  168: ['rubbish bin', 'bin bag'],
  169: ['a bird in the hand', 'kill two birds with one stone'],
  170: ['happy birthday', 'birthday party'],
  171: ['a packet of biscuits', 'chocolate biscuit'],
  173: ['bite into', 'take a bite'],
  174: ['black and white', 'black coffee'],
  176: ['a warm blanket', 'blanket coverage'],
  178: ['block the way', 'a block of'],
  179: ['blood pressure', 'blood test'],
  181: ['light blue', 'blue sky', 'feel blue'],
  183: ['by boat', 'boat trip'],
  185: ['boil water', 'boiling point'],
  197: ['boy friend', 'a boy of ten'],
  198: ['brain damage', 'use one\'s brain'],
  204: ['breathe in/out', 'out of breath'],
  205: ['cross the bridge', 'bridge over'],
  208: ['in Britain', 'Britain and France'],
  209: ['British English', 'the British'],
  210: ['a Briton', 'ancient Britons'],
  213: ['brown hair', 'brown sugar'],
  217: ['the Bund', 'on the Bund'],
  221: ['a successful businessman', 'businessman and entrepreneur'],
  224: ['butter and bread', 'butter knife'],
  225: ['butterfly effect', 'catch butterflies'],
  230: ['cabbage soup', 'Chinese cabbage'],
  231: ['café bar', 'at the café'],
  232: ['a piece of cake', 'birthday cake'],
  235: ['digital camera', 'camera phone'],
  238: ['in Canada', 'Canada and the US'],
  239: ['Canadian English', 'a Canadian'],
  242: ['team captain', 'captain of the team'],
  244: ['ID card', 'credit card', 'birthday card'],
  247: ['listen carefully', 'do sth carefully'],
  248: ['careless mistake', 'careless driver'],
  249: ['grated carrot', 'carrot juice'],
  250: ['carry on', 'carry out'],
  251: ['cartoon character', 'watch cartoons'],
  253: ['a black cat', 'let the cat out'],
  256: ['explore a cave', 'cave in'],
  257: ['celebrate sth', 'celebrate Christmas'],
  261: ['certainly not', 'certainly will'],
  262: ['a chain of', 'chain store', 'food chain'],
  263: ['sit on a chair', 'take the chair'],
  264: ['face a challenge', 'challenge sb to do sth'],
  267: ['changeable weather', 'changeable mind'],
  268: ['TV channel', 'English Channel'],
  271: ['charity event', 'charity work'],
  273: ['cheap price', 'dirt cheap'],
  276: ['cheese cake', 'a piece of cheese'],
  278: ['chemistry class', 'chemistry lab'],
  282: ['a child of', 'childhood friend'],
  283: ['in one\'s childhood', 'childhood memory'],
  286: ['Chinese food', 'Chinese New Year', 'in Chinese'],
  287: ['chocolate bar', 'a box of chocolates'],
  290: ['use chopsticks', 'a pair of chopsticks'],
  294: ['draw a circle', 'in a circle'],
  296: ['big city', 'city center', 'city life'],
  298: ['my classmate', 'old classmate'],
  299: ['in the classroom', 'clean the classroom'],
  302: ['see clearly', 'clearly stated'],
  303: ['bank clerk', 'shop clerk'],
  305: ['click on', 'double click'],
  307: ['at the clinic', 'health clinic'],
  308: ['alarm clock', 'set the clock'],
  311: ['a cloud of', 'cloud nine'],
  312: ['cloudy day', 'cloudy sky'],
  314: ['coat hanger', 'winter coat'],
  315: ['a cup of coffee', 'coffee shop'],
  316: ['a coin', 'toss a coin'],
  321: ['colour TV', 'what colour'],
  329: ['competition for', 'in competition with'],
  331: ['complete the form', 'a complete set'],
  332: ['completely different', 'completely sure'],
  336: ['press conference', 'attend a conference'],
  338: ['confident about', 'be confident'],
  344: ['work out a problem', 'work out at the gym'],
  345: ['speech contest', 'win a contest'],
  348: ['convenient for', 'convenient time'],
  350: ['cook a meal', 'cook dinner', 'a good cook'],
  355: ['answer correctly', 'do sth correctly'],
  357: ['cotton shirt', 'cotton candy'],
  360: ['developing country', 'across the country'],
  365: ['crazy about', 'go crazy'],
  366: ['ice cream', 'cream cheese'],
  367: ['dance to music', 'dance class'],
  368: ['in danger', 'out of danger'],
  370: ['dark blue', 'in the dark'],
  371: ['date back to', 'out of date'],
  373: ['son and daughter'],
  376: ['customer service', 'regular customer'],
  378: ['a day off', 'every day'],
  379: ['dead or alive', 'dead end'],
  381: ['dear friend', 'dear Sir/Madam'],
  383: ['in December', 'December holiday'],
  386: ['make a decision', 'decision making'],
  387: ['deep breath', 'deep in thought'],
  389: ['defeat sb', 'suffer a defeat'],
  390: ['defend oneself', 'defend against'],
  391: ['a delicious meal', 'delicious food'],
  393: ['a good deal', 'deal with'],
  402: ['early bird', 'early morning'],
  403: ['earn money', 'earn a living'],
  404: ['take it easy', 'easier said than done'],
  405: ['eat up', 'eat out'],
  408: ['economic development', 'economic growth'],
  409: ['educational system', 'educational background'],
  410: ['effective way', 'effective measure'],
  411: ['make an effort', 'spare no effort'],
  413: ['either...or', 'on either side'],
  414: ['elder brother', 'elder sister'],
  415: ['be elected', 'election campaign'],
  416: ['electric fan', 'electric power'],
  417: ['electronic product', 'electronic mail'],
  418: ['elementary school', 'elementary education'],
  419: ['elephant tusk', 'see an elephant'],
  420: ['elevator button', 'take the elevator'],
  421: ['dialogue between', 'have a dialogue'],
  423: ['end up', 'in the end', 'at the end of'],
  425: ['enjoy doing', 'enjoy oneself'],
  426: ['enjoyable trip', 'enjoyable experience'],
  427: ['enough time', 'good enough'],
  428: ['enter the room', 'enter for'],
  429: ['entire life', 'entire family'],
  430: ['dig up', 'dig a hole'],
  432: ['dining hall', 'dining room'],
  433: ['dinner party', 'have dinner'],
  435: ['direct flight', 'direct result'],
  436: ['change direction', 'in the direction of'],
  437: ['film director', 'director of'],
  439: ['discover sth', 'discover that'],
  441: ['discuss sth with sb', 'under discussion'],
  443: ['a dish of', 'main dish'],
  445: ['on display', 'display window'],
  446: ['distance learning', 'in the distance'],
  447: ['do homework', 'do one\'s best'],
  449: ['see a doctor', 'doctor\'s degree'],
  450: ['keep a diary', 'write in one\'s diary'],
  452: ['look up in a dictionary', 'dictionary definition'],
  455: ['a healthy diet', 'on a diet'],
  456: ['differ from', 'different from'],
  458: ['difficult to', 'have difficulty doing'],
  460: ['dig a hole', 'dig out'],
  462: ['digital camera', 'digital age'],
  463: ['dining hall', 'dining room'],
  465: ['direct answer', 'direct flight'],
  466: ['in the direction of', 'change direction'],
  467: ['film director', 'director general'],
  468: ['dirty water', 'dirty hands'],
  470: ['on duty', 'off duty'],
  471: ['each other', 'each of'],
  472: ['eager to', 'eager for'],
  473: ['eagle eye', 'bald eagle'],
  475: ['early bird', 'in the early morning'],
  476: ['earn a living', 'earn money'],
  477: ['on earth', 'down to earth'],
  478: ['easily done', 'more easily'],
  479: ['east of', 'in the east'],
  480: ['easy going', 'take it easy'],
  481: ['eat out', 'eat up'],
  482: ['ecological balance'],
  483: ['on the edge', 'edge of'],
  486: ['make an effort', 'no effort'],
  487: ['either side', 'either way'],
  488: ['elder people', 'respect elders'],
  489: ['be elected as', 'presidential election'],
  490: ['electricity bill', 'cut off electricity'],
  491: ['electronic dictionary', 'electronic product'],
  492: ['elementary school', 'elementary level'],
  493: ['elephant trunk', 'African elephant'],
  494: ['something else', 'or else'],
  495: ['e-mail address', 'send an e-mail'],
  496: ['in an emergency', 'emergency room'],
  497: ['emergency call', 'state of emergency'],
  498: ['emotional support', 'emotion control'],
  499: ['employ sb', 'employer and employee'],
  500: ['encourage sb to do', 'be encouraged by'],
  501: ['in the end', 'end up'],
  502: ['enemy of', 'make enemies'],
  503: ['full of energy', 'energy drink'],
  504: ['engage in', 'be engaged to'],
  505: ['English class', 'spoken English'],
  506: ['enjoy doing', 'enjoy life'],
  507: ['enjoyable weekend', 'enjoyable trip'],
  508: ['enough for', 'not enough'],
  509: ['enter for', 'enter the room'],
  510: ['entertainment industry', 'live entertainment'],
  511: ['enthusiastic about', 'show enthusiasm'],
  512: ['entire day', 'entire family'],
  513: ['entrance exam', 'at the entrance'],
  514: ['in the envelope'],
  515: ['environment protection', 'environment friendly'],
  516: ['especially for', 'especially when'],
  517: ['evening dress', 'in the evening'],
  518: ['event organizer', 'sporting event'],
  519: ['ever since', 'for ever'],
  520: ['every day', 'every time'],
  521: ['everybody else', 'almost everybody'],
  522: ['everyday life', 'everyday use'],
  523: ['everyone knows', 'everyone else'],
  524: ['everything else', 'do everything'],
  525: ['everywhere in', 'almost everywhere'],
  526: ['evidence for', 'scientific evidence'],
  527: ['evil spirit', 'the evil'],
  528: ['exact time', 'to be exact'],
  529: ['take an exam', 'medical examination'],
  530: ['for example', 'set an example'],
  531: ['excellent at', 'excellent result'],
  532: ['except for', 'except that'],
  533: ['exciting news', 'exciting game'],
  534: ['excuse me', 'make an excuse'],
  535: ['do exercise', 'take exercise'],
  536: ['art exhibition', 'on exhibition'],
  537: ['exist in', 'exist on'],
  538: ['emergency exit', 'exit from'],
  539: ['an exciting match', 'expand business'],
  540: ['expect to', 'as expected'],
  541: ['too expensive', 'expensive gift'],
  542: ['gain experience', 'experienced in'],
  543: ['do an experiment', 'an experiment on'],
  544: ['expert at/in', 'an expert on'],
  545: ['explain sth to sb', 'explanation for'],
  546: ['explore the world', 'explore possibilities'],
  548: ['express oneself', 'facial expression'],
  549: ['extra work', 'no extra charge'],
  550: ['extreme sport', 'go to extremes'],
  551: ['eye contact', 'keep an eye on'],
  552: ['good eyesight', 'poor eyesight'],
  553: ['face to face', 'face the challenge'],
  554: ['in fact', 'as a matter of fact'],
  555: ['factory worker', 'factory building'],
  556: ['fail to', 'fail the exam'],
  557: ['failure in', 'end in failure'],
  558: ['fair play', 'fair price'],
  559: ['fall asleep', 'fall behind', 'fall in love with'],
  560: ['false alarm', 'true or false'],
  562: ['famous for', 'famous as'],
  563: ['far away', 'far from', 'so far'],
  564: ['on the farm', 'farm house'],
  565: ['fast food', 'fast train'],
  566: ['fat free', 'get fat'],
  567: ['father and son', 'father figure'],
  568: ['my fault', 'find fault with'],
  569: ['do sb a favour', 'in favour of'],
  570: ['favourite food', 'my favourite'],
  571: ['fear of', 'in fear'],
  572: ['in February', 'February 14th'],
  573: ['feed on', 'be fed up with'],
  574: ['feel like', 'feel free'],
  575: ['a few', 'only a few'],
  576: ['field trip', 'in the field'],
  577: ['fight against', 'fight for'],
  579: ['film star', 'see a film'],
  580: ['final exam', 'final decision'],
  581: ['find out', 'find one\'s way'],
  582: ['by ferry', 'ferry boat'],
  583: ['have a fever', 'run a fever'],
  584: ['quite a few', 'few of them'],
  585: ['field trip', 'in the field of'],
  586: ['fight back', 'fight for one\'s rights'],
  587: ['figure out', 'figure of speech'],
  588: ['fill in the blank', 'be filled with'],
  589: ['final result', 'final exam'],
  590: ['find out', 'find sb doing sth'],
  591: ['fine weather', 'fine art'],
  592: ['finger print', 'cross one\'s fingers'],
  593: ['finish line', 'finish doing'],
  594: ['on fire', 'catch fire', 'fire alarm'],
  595: ['first of all', 'at first', 'first aid'],
  596: ['go fishing', 'fish tank'],
  597: ['fit in', 'fit for', 'keep fit'],
  598: ['a five-star hotel', 'five years old'],
  599: ['fix up', 'fix the problem'],
  600: ['flash light', 'in a flash'],
  601: ['flat tire', 'flat screen'],
  602: ['a flight to', 'flight number'],
  603: ['floor plan', 'ground floor'],
  604: ['flour and water', 'flour mill'],
  605: ['flow chart', 'cash flow'],
  606: ['a bunch of flowers', 'flower shop'],
  607: ['catch the flu', 'bird flu'],
  608: ['flush the toilet'],
  609: ['focus on', 'out of focus'],
  610: ['fold up', 'fold one\'s arms'],
  611: ['follow sb', 'as follows'],
  612: ['fond of', 'be fond of doing'],
  613: ['fool around', 'make a fool of'],
  614: ['on foot', 'at the foot of'],
  615: ['for example', 'for sure', 'for good'],
  616: ['forbid sb to do', 'forbidden area'],
  617: ['force sb to do', 'by force'],
  618: ['weather forecast', 'forecast weather'],
  619: ['foreign country', 'foreign language'],
  620: ['foresee the future', 'foresee problems'],
  621: ['forest fire', 'in the forest'],
  622: ['forget about', 'forget to do'],
  623: ['forgive sb for', 'forgive and forget'],
  624: ['form a habit', 'application form'],
  625: ['former president', 'the former...the latter'],
  627: ['fortunate to', 'be fortunate in'],
  628: ['fortunately for'],
  629: ['look forward to', 'bring forward'],
  630: ['be founded in', 'found a company'],
  631: ['fountain pen', 'fountain of youth'],
  632: ['as cunning as a fox'],
  633: ['fragile item', 'fragile glass'],
  634: ['free of charge', 'free time', 'set free'],
  635: ['freedom of speech'],
  636: ['freeze to death', 'freezing point'],
  637: ['fresh air', 'fresh water'],
  638: ['on Friday', 'Black Friday'],
  639: ['in the fridge', 'fridge door'],
  640: ['make friends with', 'best friend'],
  641: ['be frightened of', 'frighten sb'],
  642: ['from now on', 'from time to time'],
  643: ['in front of', 'in the front of'],
  644: ['fruit juice', 'fresh fruit'],
  645: ['fry pan', 'stir fry'],
  646: ['full of', 'full time'],
  647: ['have fun', 'make fun of'],
  648: ['a piece of furniture', 'furniture store'],
  649: ['further study', 'further information'],
  650: ['future plan', 'in the future'],
  651: ['gain weight', 'gain knowledge'],
  652: ['game over', 'Olympic Games'],
  653: ['garbage can', 'take out the garbage'],
  654: ['in the garden', 'garden city'],
  655: ['gas station', 'natural gas'],
  656: ['gateway to'],
  657: ['in general', 'general manager'],
  658: ['generation gap', 'from generation to generation'],
  659: ['generous to', 'be generous with'],
  660: ['gentle man', 'ladies and gentlemen'],
  661: ['geography class', 'physical geography'],
  662: ['German car', 'in German'],
  663: ['in Germany'],
  664: ['get up', 'get on', 'get off'],
  665: ['birthday gift', 'a gift for'],
  666: ['see a giraffe'],
  667: ['girl friend', 'a little girl'],
  668: ['give up', 'give in', 'give away'],
  669: ['glad to', 'be glad about'],
  670: ['a glass of water', 'glass window'],
  671: ['global warming', 'global market'],
  672: ['a pair of gloves', 'take off gloves'],
  673: ['glue stick', 'super glue'],
  674: ['go ahead', 'go on', 'go through'],
  675: ['achieve a goal', 'set a goal'],
  676: ['gold medal', 'gold mine'],
  677: ['golden chance', 'golden hair'],
  678: ['good at', 'good for'],
  679: ['say goodbye', 'goodbye to'],
  680: ['grade A', 'get good grades'],
  681: ['graduation ceremony', 'after graduation'],
  682: ['grand parents', 'grand child'],
  683: ['grandson and granddaughter'],
  684: ['my grandfather', 'grandfather clock'],
  685: ['my grandmother'],
  686: ['a grandson of'],
  687: ['a bunch of grapes', 'grape juice'],
  688: ['on the grass', 'green grass'],
  689: ['a great deal', 'a great many'],
  690: ['green tea', 'green house'],
  692: ['ground floor', 'on the ground'],
  693: ['a group of', 'in groups'],
  694: ['grow up', 'grow into'],
  695: ['guard against', 'off guard'],
  696: ['guess what', 'make a guess'],
  697: ['tour guide', 'guide sb to'],
  698: ['play the guitar', 'guitar player'],
  700: ['form a habit', 'break the habit'],
  701: ['hair cut', 'hair style'],
  702: ['go to the hairdresser'],
  703: ['half of', 'half an hour'],
  704: ['concert hall', 'dining hall'],
  705: ['eat a hamburger'],
  706: ['hand in', 'hand out', 'give a hand'],
  707: ['designer handbag'],
  708: ['handsome boy', 'handsome reward'],
  709: ['handwriting', 'handwriting on the wall'],
  710: ['hang on', 'hang up', 'hang out with'],
  711: ['happen to', 'as it happens'],
  712: ['happy birthday', 'happy about'],
  713: ['hard work', 'work hard'],
  714: ['hardly...when', 'hardly anyone'],
  715: ['harmful to', 'do harm to'],
  716: ['wear a hat', 'hat and coat'],
  717: ['hate doing', 'hate to do'],
  718: ['have to', 'had better'],
  719: ['he who', 'he himself'],
  720: ['head for', 'use one\'s head'],
  721: ['have a headache'],
  722: ['school headmaster'],
  723: ['health care', 'in good health'],
  724: ['hear from', 'hear of'],
  725: ['heart attack', 'by heart', 'lose heart'],
  726: ['heat up', 'heat wave'],
  727: ['heavy rain', 'heavy traffic'],
  728: ['in height', 'height of'],
  729: ['say hello', 'hello there'],
  730: ['help sb with', 'with the help of'],
  731: ['helpful to', 'be helpful for'],
  732: ['a hen laying eggs', 'hen house'],
  733: ['of her own'],
  734: ['here and there', 'here we go'],
  735: ['national hero', 'hero of'],
  736: ['by herself', 'for herself'],
  737: ['hey there'],
  738: ['say hi to', 'hi everyone'],
  739: ['hide and seek', 'hide from'],
  740: ['high school', 'high quality'],
  741: ['go hiking', 'hiking boots'],
  742: ['on top of the hill', 'over the hill'],
  743: ['by himself', 'for himself'],
  744: ['hire sb', 'for hire'],
  745: ['of his', 'his own'],
  746: ['in history', 'make history'],
  747: ['hit the target', 'a big hit'],
  748: ['hobby group', 'hobby and interest'],
  749: ['hold on', 'hold back', 'hold a meeting'],
  750: ['a hole in'],
  751: ['on holiday', 'summer holiday'],
  752: ['go home', 'at home', 'home town'],
  753: ['do homework', 'hand in homework'],
  754: ['to be honest', 'honestly speaking'],
  755: ['honey moon', 'honey bee'],
  756: ['from Hong Kong'],
  757: ['hope for', 'hope to do'],
  758: ['horse riding', 'on horse back'],
  759: ['in hospital', 'go to hospital'],
  760: ['hot dog', 'hot spring'],
  761: ['hotel room', 'stay at a hotel'],
  762: ['per hour', 'rush hour'],
  763: ['house work', 'house wife'],
  764: ['how about', 'how come', 'how far'],
  765: ['no matter how'],
  766: ['a huge amount of', 'huge success'],
  767: ['human being', 'human rights'],
  768: ['hundreds of', 'one hundred'],
  769: ['go hungry', 'feel hungry'],
  771: ['hurry up', 'in a hurry'],
  772: ['hurt oneself', 'get hurt'],
  773: ['ice cream', 'on thin ice'],
  774: ['have an idea', 'good idea'],
  775: ['as if', 'even if', 'if only'],
  776: ['fall ill', 'ill in bed'],
  777: ['suffer from illness', 'serious illness'],
  778: ['imagine doing', 'use one\'s imagination'],
  779: ['immediate action', 'immediate family'],
  780: ['of great importance', 'attach importance to'],
  781: ['important to', 'play an important role'],
  782: ['impossible to', 'next to impossible'],
  783: ['improve in', 'improve the situation'],
  784: ['in other words', 'in fact', 'in all'],
  785: ['inch by inch', 'every inch'],
  786: ['included in', 'including but not limited to'],
  787: ['increase by', 'on the increase'],
  788: ['very much indeed'],
  789: ['independent of', 'be independent from'],
  790: ['indicate that', 'indication of'],
  791: ['indoor activity', 'indoor swimming pool'],
  792: ['industrial area', 'industrial revolution'],
  793: ['service industry', 'IT industry'],
  794: ['be infected by', 'infect with'],
  795: ['influence on', 'under the influence of'],
  796: ['inform sb of', 'keep sb informed'],
  797: ['information about', 'a piece of information'],
  798: ['active ingredient'],
  799: ['initial stage', 'in the initial phase'],
  800: ['be injured', 'the injured'],
  801: ['in ink', 'ink pen'],
  802: ['country inn'],
  803: ['inner city', 'inner world'],
  804: ['inside out', 'inside the box'],
  805: ['insist on', 'insist that'],
  806: ['inspire sb to do', 'draw inspiration from'],
  807: ['install sth', 'installation guide'],
  808: ['instead of'],
  809: ['research institute', 'institute of'],
  810: ['follow instructions', 'instruction manual'],
  811: ['musical instrument', 'play an instrument'],
  812: ['insurance company', 'life insurance'],
  813: ['intellectual property'],
  814: ['artificial intelligence'],
  815: ['intend to', 'be intended for'],
  816: ['interest in', 'lose interest in'],
  817: ['an interesting story', 'interesting book'],
  818: ['interfere with', 'interference in'],
  819: ['internal affairs', 'internal medicine'],
  820: ['international trade', 'international student'],
  821: ['on the Internet', 'Internet access'],
  823: ['don\'t interrupt', 'interrupt sb'],
  824: ['at intervals', 'during the interval'],
  825: ['job interview', 'have an interview'],
  826: ['get into', 'look into'],
  827: ['introduce sb to', 'introduction to'],
  828: ['invent sth', 'invention of'],
  829: ['invest in', 'investment in'],
  830: ['invite sb to', 'invitation to'],
  831: ['be involved in', 'involve in'],
  832: ['iron shirt', 'strike while the iron is hot'],
  833: ['on the island', 'desert island'],
  834: ['issue of', 'issue a statement'],
  835: ['by itself', 'in itself'],
  836: ['life jacket', 'wear a jacket'],
  837: ['in January', 'January 1st'],
  838: ['a jar of jam', 'cookie jar'],
  839: ['jazz music', 'jazz club'],
  840: ['a pair of jeans', 'jeans and T-shirt'],
  841: ['drive a jeep'],
  842: ['jet lag', 'jet plane'],
  843: ['wear jewelry', 'jewelry store'],
  844: ['job market', 'apply for a job', 'lose one\'s job'],
  845: ['go jogging', 'jog in the park'],
  846: ['join in', 'join the army'],
  847: ['play a joke on', 'make a joke'],
  848: ['keep a journal', 'academic journal'],
  849: ['journey to', 'have a good journey'],
  850: ['with joy', 'full of joy'],
  851: ['judge by', 'judging from'],
  852: ['a glass of juice', 'orange juice'],
  853: ['in July', 'July 4th'],
  854: ['jump over', 'high jump'],
  855: ['in June', 'June 1st'],
  856: ['junior high', 'junior to'],
  857: ['just now', 'just in time'],
  858: ['keep on', 'keep up with', 'keep in touch'],
  859: ['key to', 'car key'],
  860: ['type on the keyboard', 'keyboard player'],
  861: ['kick off', 'kick the ball'],
  862: ['just kidding', 'kid around'],
  863: ['kill time', 'kill two birds'],
  864: ['half a kilo', 'a kilo of apples'],
  865: ['a kind of', 'all kinds of', 'be kind to'],
  866: ['king of', 'lion king'],
  867: ['kiss goodbye', 'blow a kiss'],
  868: ['in the kitchen', 'kitchen table'],
  869: ['fly a kite', 'go fly a kite'],
  870: ['on one\'s knees', 'knee injury'],
  871: ['knife and fork', 'sharp knife'],
  872: ['knock at', 'knock on', 'knock down'],
  873: ['know about', 'as far as I know'],
  874: ['knowledge of', 'common knowledge'],
  875: ['in the lab', 'lab report'],
  876: ['label on', 'read the label'],
  877: ['physical labor', 'labor market'],
  878: ['lack of', 'for lack of'],
  879: ['climb the ladder', 'social ladder'],
  880: ['lady first', 'ladies\' room'],
  881: ['by the lake', 'on the lake'],
  882: ['turn on the lamp', 'table lamp'],
  883: ['land on', 'land use'],
  884: ['first language', 'foreign language', 'body language'],
  885: ['at large', 'by and large'],
  886: ['at last', 'last name', 'last year'],
  887: ['be late', 'late for'],
  888: ['laugh at', 'laugh out loud'],
  889: ['launch a product'],
  890: ['do the laundry', 'laundry room'],
  891: ['break the law', 'pass a law', 'by law'],
  892: ['on the lawn', 'lawn mower'],
  893: ['hire a lawyer', 'defense lawyer'],
  894: ['lay the table', 'lay off', 'lay out'],
  895: ['too lazy to', 'lazy bones'],
  896: ['lead to', 'take the lead', 'in the lead'],
  897: ['turn over a new leaf', 'green leaves'],
  898: ['lean against', 'lean on'],
  899: ['learn from', 'learn by heart'],
  900: ['at least', 'not in the least'],
  901: ['leave alone', 'leave behind', 'leave for'],
  902: ['give a lecture', 'attend a lecture'],
  903: ['on the left', 'turn left'],
  904: ['on one\'s last legs', 'leg pain'],
  905: ['legal advice', 'legal age'],
  906: ['lemon juice', 'lemon tree'],
  907: ['lend sth to sb', 'lend a hand'],
  908: ['at length', 'in length'],
  909: ['less than', 'more or less'],
  910: ['have a lesson', 'lesson plan'],
  911: ['let down', 'let go', 'let me see'],
  912: ['write a letter', 'by letter', 'capital letter'],
  913: ['sea level', 'on the level'],
  914: ['library card', 'borrow from the library'],
  915: ['driver\'s license', 'business license'],
  916: ['lie down', 'lie in', 'tell a lie'],
  917: ['way of life', 'daily life', 'come to life'],
  918: ['give sb a lift', 'take the lift'],
  919: ['turn on the light', 'traffic light', 'green light'],
  920: ['feel like', 'would like to'],
  921: ['likely to', 'most likely'],
  922: ['time limit', 'speed limit', 'within limits'],
  923: ['line up', 'in line with'],
  924: ['link to', 'a link between'],
  925: ['lion king', 'as brave as a lion'],
  926: ['lip stick', 'on one\'s lips'],
  927: ['on the list', 'make a list'],
  928: ['listen to', 'listen carefully'],
  929: ['English literature', 'classical literature'],
  930: ['no littering', 'drop litter'],
  931: ['little by little', 'a little'],
  932: ['live in', 'live on', 'live up to'],
  933: ['a load of', 'take a load off'],
  934: ['local time', 'local people', 'local government'],
  935: ['lock the door', 'lock up'],
  936: ['log in', 'log out', 'log on'],
  937: ['in London', 'London Bridge'],
  938: ['feel lonely', 'lonely planet'],
  939: ['long for', 'as long as', 'no longer'],
  940: ['look at', 'look for', 'look after', 'look forward to'],
  941: ['lose weight', 'lose face', 'lose heart'],
  942: ['a lot of', 'lots of'],
  943: ['loud noise', 'loud speaker'],
  944: ['fall in love', 'would love to'],
  945: ['low price', 'low temperature'],
  946: ['good luck', 'bad luck', 'in luck'],
  947: ['lucky dog', 'lucky enough'],
  948: ['have lunch', 'lunch time'],
  949: ['lung cancer'],
  950: ['vending machine', 'washing machine'],
  951: ['mad about', 'go mad', 'drive sb mad'],
  952: ['read a magazine', 'monthly magazine'],
  953: ['magic show', 'as if by magic'],
  954: ['send a mail', 'by mail', 'mail box'],
  955: ['main street', 'main reason'],
  956: ['major in', 'major problem'],
  957: ['make up', 'make sure', 'make sense'],
  958: ['male and female', 'male teacher'],
  959: ['shopping mall', 'go to the mall'],
  960: ['manage to', 'manage a company'],
  961: ['a good many', 'how many'],
  962: ['map of', 'on the map', 'road map'],
  963: ['in March', 'March 8th'],
  964: ['full marks', 'get good marks'],
  965: ['stock market', 'market share'],
  966: ['marry sb', 'get married', 'be married to'],
  967: ['master degree', 'master piece'],
  968: ['football match', 'match...with'],
  969: ['math problem', 'do math'],
  970: ['what\'s the matter', 'no matter'],
  971: ['in May', 'May Day'],
  972: ['maybe not'],
  973: ['excuse me', 'me too'],
  974: ['have a meal', 'meal time'],
  975: ['mean to', 'what do you mean'],
  976: ['meaning of', 'meaningful life'],
  977: ['red meat', 'fresh meat'],
  978: ['medical care', 'medical check'],
  979: ['take medicine', 'medicine for'],
  980: ['meet the need', 'meet with'],
  981: ['meeting room', 'have a meeting'],
  982: ['melt away', 'melting point'],
  983: ['team member', 'family member'],
  984: ['in memory of', 'from memory'],
  985: ['on the mend'],
  986: ['mental health', 'make up one\'s mind'],
  987: ['don\'t mention it', 'not to mention'],
  988: ['on the menu', 'menu card'],
  989: ['not merely...but also'],
  990: ['merry Christmas', 'merry go round'],
  991: ['leave a message', 'take a message', 'text message'],
  992: ['heavy metal', 'metal detector'],
  993: ['teaching method', 'scientific method'],
  994: ['middle school', 'in the middle of'],
  995: ['might as well'],
  996: ['a glass of milk', 'milk shake'],
  997: ['change one\'s mind', 'make up one\'s mind'],
  998: ['a friend of mine'],
  999: ['mineral water', 'mineral resource'],
  1000: ['prime minister', 'minister of'],
  1001: ['in a minute', 'wait a minute'],
  1002: ['look in the mirror', 'mirror image'],
  1003: ['miss the bus', 'miss sb'],
  1004: ['by mistake', 'make a mistake'],
  1005: ['mix up', 'mix with'],
  1006: ['mobile phone', 'on mobile'],
  1007: ['role model', 'fashion model'],
  1008: ['modern art', 'modern times'],
  1009: ['mom and dad'],
  1010: ['on Monday', 'Monday morning'],
  1011: ['make money', 'save money'],
  1012: ['class monitor', 'computer monitor'],
  1013: ['monkey business', 'make a monkey of'],
  1014: ['last month', 'next month'],
  1015: ['in a good mood', 'bad mood'],
  1016: ['moon cake', 'full moon', 'on the moon'],
  1017: ['moral standard', 'moral support'],
  1018: ['more than', 'the more...the more'],
  1019: ['in the morning', 'morning paper'],
  1020: ['at most', 'make the most of'],
  1021: ['mother tongue', 'mother land'],
  1022: ['motor bike', 'motor cycle'],
  1023: ['mountain climbing', 'mountain top'],
  1024: ['computer mouse', 'as quiet as a mouse'],
  1025: ['keep one\'s mouth shut', 'by word of mouth'],
  1026: ['move on', 'move to', 'move house'],
  1027: ['movie star', 'go to the movies'],
  1028: ['too much', 'as much as'],
  1029: ['history museum', 'art museum'],
  1030: ['listen to music', 'pop music'],
  1031: ['must be', 'must have done'],
  1032: ['by myself', 'for myself'],
  1033: ['finger nail', 'hit the nail on the head'],
  1034: ['name after', 'in the name of'],
  1035: ['narrow down', 'narrow escape'],
  1036: ['nation wide', 'United Nations'],
  1037: ['national flag', 'national day'],
  1038: ['native language', 'native speaker'],
  1039: ['natural disaster', 'natural beauty'],
  1040: ['in nature', 'by nature'],
  1041: ['near by', 'near to'],
  1042: ['not nearly'],
  1043: ['if necessary', 'necessary for'],
  1044: ['neck tie', 'neck and neck'],
  1045: ['in need of', 'meet the need'],
  1046: ['as sharp as a needle', 'thread a needle'],
  1047: ['negative effect', 'negative attitude'],
  1048: ['neither...nor', 'neither of', 'me neither'],
  1049: ['my nephew'],
  1050: ['feel nervous', 'nervous about'],
  1051: ['on the net', 'net weight'],
  1052: ['never mind', 'never before'],
  1053: ['new year', 'Happy New Year', 'brand new'],
  1054: ['good news', 'bad news', 'on the news'],
  1055: ['read a newspaper', 'in the newspaper'],
  1056: ['next to', 'next door', 'next time'],
  1057: ['nice to meet you', 'nice and warm'],
  1058: ['my niece'],
  1059: ['at night', 'good night', 'midnight'],
  1060: ['nine out of ten', 'nine to five'],
  1061: ['no one', 'no more', 'no longer'],
  1062: ['nobody else', 'nobody knows'],
  1063: ['nod one\'s head', 'nod off'],
  1064: ['make a noise', 'too much noise'],
  1065: ['none of', 'second to none'],
  1066: ['rice noodle', 'instant noodle'],
  1067: ['at noon', 'by noon'],
  1068: ['neither...nor', 'nor do I'],
  1069: ['back to normal', 'normal temperature'],
  1070: ['in the north', 'North America'],
  1071: ['runny nose', 'as plain as the nose'],
  1072: ['take notes', 'leave a note'],
  1073: ['nothing but', 'for nothing'],
  1074: ['notice board', 'take notice of'],
  1075: ['in November', 'November 11th'],
  1076: ['by now', 'from now on', 'just now'],
  1077: ['get nowhere', 'out of nowhere'],
  1078: ['nuclear energy', 'nuclear weapon'],
  1079: ['a number of', 'the number of', 'phone number'],
  1080: ['see a nurse', 'nursing home'],
  1081: ['a tough nut to crack', 'peanut'],
  1082: ['obey the rules', 'obey orders'],
  1083: ['object to', 'an object of'],
  1084: ['observe sth', 'observe that'],
  1085: ['it\'s obvious that'],
  1086: ['on occasion', 'special occasion'],
  1087: ['be occupied with'],
  1088: ['it occurred to me that'],
  1089: ['in the ocean', 'Pacific Ocean'],
  1090: ['at 3 o\'clock'],
  1091: ['in October', 'October 1st'],
  1092: ['of course', 'because of'],
  1093: ['off duty', 'day off', 'take off'],
  1094: ['offer to', 'offer sb sth'],
  1095: ['office building', 'post office'],
  1096: ['police officer', 'army officer'],
  1097: ['government official', 'official language'],
  1098: ['very often', 'how often'],
  1099: ['oh my god', 'oh dear'],
  1100: ['cooking oil', 'olive oil'],
  1101: ['that\'s OK', 'OK then'],
  1102: ['how old', 'old friend', 'old days'],
  1103: ['on time', 'on duty', 'and so on'],
  1104: ['at once', 'once upon a time', 'once more'],
  1105: ['one by one', 'one of'],
  1106: ['by oneself', 'for oneself'],
  1107: ['go online', 'online shopping'],
  1108: ['not only...but also', 'if only'],
  1109: ['get onto'],
  1110: ['open up', 'open the door', 'opening hours'],
  1111: ['operate on', 'operate a machine'],
  1112: ['in one\'s opinion', 'public opinion'],
  1113: ['have the opportunity to', 'job opportunity'],
  1114: ['opposite to', 'on the opposite side'],
  1115: ['or else', 'or so'],
  1116: ['orange juice', 'orange tree'],
  1117: ['put in order', 'in order to', 'out of order'],
  1118: ['in ordinary', 'ordinary people'],
  1119: ['paint a picture', 'oil paint'],
  1120: ['a pair of', 'in pairs'],
  1121: ['palace museum', 'Buckingham Palace'],
  1122: ['pale face', 'pale blue'],
  1123: ['pan cake', 'frying pan'],
  1124: ['panda bear', 'giant panda'],
  1125: ['paper work', 'a piece of paper'],
  1126: ['pardon me', 'beg one\'s pardon'],
  1127: ['parents and children', 'parent teacher meeting'],
  1128: ['park the car', 'in the park', 'car park'],
  1129: ['part of', 'take part in', 'play a part in'],
  1130: ['take part in', 'part time job'],
  1131: ['pass the exam', 'pass by', 'pass away'],
  1132: ['password', 'forget one\'s password'],
  1133: ['in the past', 'past tense'],
  1134: ['path to', 'cross one\'s path'],
  1135: ['be patient with', 'patient enough to'],
  1136: ['pay for', 'pay attention to', 'pay back'],
  1137: ['PE class', 'PE teacher'],
  1138: ['PE class', 'PE lesson'],
  1139: ['PE class', 'PE teacher'],
  1140: ['peace and quiet', 'in peace', 'world peace'],
  1141: ['peach tree', 'peach juice'],
  1142: ['pear tree', 'sweet pear'],
  1143: ['a pen friend', 'pen name', 'ballpoint pen'],
  1144: ['pencil box', 'pencil sharpener'],
  1145: ['penguin', 'penguin habitat'],
  1146: ['people\'s republic', 'many people'],
  1147: ['pepper and salt', 'black pepper'],
  1148: ['per cent', '100 percent'],
  1149: ['perfect for', 'be perfect'],
  1150: ['perform a task', 'perform well'],
  1151: ['perhaps so', 'perhaps not'],
  1152: ['period of time', 'in a period'],
  1153: ['personal information', 'personal opinion'],
  1154: ['pet dog', 'pet shop'],
  1155: ['petrol station', 'petrol tank'],
  1156: ['phone number', 'phone call', 'on the phone'],
  1157: ['photo graph', 'take a photo', 'photo album'],
  1158: ['piano lesson', 'play the piano'],
  1159: ['pick up', 'pick out', 'pick and choose'],
  1160: ['picnic lunch', 'go for a picnic'],
  1161: ['a picture of', 'take a picture'],
  1162: ['a piece of', 'piece by piece'],
  1163: ['pig meat', 'pig sty'],
  1164: ['pigeon', 'carrier pigeon'],
  1165: ['a pile of', 'pile up'],
  1166: ['pillow case', 'pillow fight'],
  1167: ['a pilot of', 'pilot license'],
  1168: ['in pink', 'pink ribbon'],
  1169: ['pioneer in', 'Young Pioneer'],
  1170: ['pizza hut', 'a slice of pizza'],
  1171: ['a place of interest', 'take place', 'place of birth'],
  1172: ['plain clothes', 'plain English', 'plain food'],
  1173: ['plan to', 'plan for', 'make a plan'],
  1174: ['air plane', 'by plane', 'plane ticket'],
  1175: ['plant trees', 'power plant'],
  1176: ['plastic bag', 'plastic surgery'],
  1177: ['paper plate', 'plate of food'],
  1178: ['platform ticket', 'on the platform'],
  1179: ['play ground', 'play a game', 'play with'],
  1180: ['pleasant trip', 'pleasant weather'],
  1181: ['please me', 'as you please'],
  1182: ['be pleased with', 'pleased to meet you'],
  1183: ['plenty of', 'plenty of time'],
  1184: ['pocket money', 'in one\'s pocket'],
  1185: ['a poem about', 'write a poem'],
  1186: ['point of view', 'point out', 'point to'],
  1187: ['poisonous snake', 'rat poison'],
  1188: ['police station', 'call the police', 'police officer'],
  1189: ['in the afternoon', '3 p.m.'],
  1190: ['be polite to', 'politely'],
  1191: ['pollute the environment', 'polluted air'],
  1192: ['a pool of', 'swimming pool'],
  1193: ['poor at', 'poor people', 'the poor'],
  1194: ['pop music', 'pop star', 'pop up'],
  1195: ['popular with', 'popular among'],
  1196: ['a portion of', 'portion size'],
  1197: ['position of', 'in position'],
  1198: ['be positive about', 'positive attitude'],
  1199: ['possible to', 'as...as possible', 'if possible'],
  1200: ['post office', 'post card', 'post box'],
  1201: ['poster of', 'put up a poster'],
  1202: ['pour into', 'pour out'],
  1203: ['powder snow', 'baking powder'],
  1204: ['be powerful enough', 'powerful weapon'],
  1205: ['practical use', 'practical experience'],
  1206: ['praise sb for', 'in praise of'],
  1207: ['prefer to', 'prefer...rather than'],
  1208: ['prepare for', 'be prepared'],
  1209: ['present for', 'at present', 'be present'],
  1210: ['press the button', 'press conference'],
  1211: ['pretend to', 'pretend that'],
  1212: ['pretty good', 'pretty much'],
  1213: ['prevent from', 'prevent sth'],
  1214: ['price tag', 'at a price', 'price list'],
  1215: ['primary school', 'primary purpose'],
  1216: ['print out', 'in print', 'print a document'],
  1217: ['private life', 'in private'],
  1218: ['prize winner', 'first prize', 'win a prize'],
  1219: ['probably not', 'probably yes'],
  1220: ['a big problem', 'solve a problem', 'problem solving'],
  1221: ['process of', 'in the process'],
  1222: ['produce sth', 'made in China'],
  1223: ['product of', 'product development'],
  1224: ['profession al', 'professional skill'],
  1225: ['professor of', 'associate professor'],
  1226: ['make a profit', 'profit from'],
  1227: ['program of', 'TV program', 'computer program'],
  1228: ['project plan', 'do a project'],
  1229: ['promise to', 'make a promise', 'keep a promise'],
  1230: ['promote sth', 'promote to'],
  1231: ['pronunciation of', 'practice pronunciation'],
  1232: ['proof of', 'read the proof'],
  1233: ['proper way', 'proper noun'],
  1234: ['protect from', 'protect sb from', 'environment protection'],
  1235: ['be proud of', 'proud to'],
  1236: ['prove that', 'prove sb wrong'],
  1237: ['provide sb with', 'provide for'],
  1238: ['province', 'in the province'],
  1239: ['public school', 'in public', 'public holiday'],
  1240: ['pull over', 'pull down', 'pull together'],
  1241: ['punish sb for', 'punishment for'],
  1242: ['pupil of', 'primary school pupil'],
  1243: ['pure water', 'pure gold'],
  1244: ['purple', 'in purple', 'turn purple'],
  1245: ['purpose of', 'on purpose', 'for the purpose of'],
  1246: ['push up', 'push the door', 'push back'],
  1247: ['put on', 'put up', 'put off', 'put away'],
  1248: ['quality of', 'high quality', 'quality time'],
  1249: ['quantum', 'quantum physics'],
  1250: ['a quarter of', 'a quarter past'],
  1251: ['queue up', 'in a queue', 'jump the queue'],
  1252: ['be quiet', 'keep quiet', 'peace and quiet'],
  1253: ['quite a few', 'quite good', 'quite sure'],
  1254: ['race car', 'win a race', 'horse race'],
  1255: ['radio program', 'on the radio', 'radio station'],
  1256: ['railway station', 'by rail'],
  1257: ['rain cats and dogs', 'rainy day', 'heavy rain'],
  1258: ['raise hand', 'raise money', 'raise a family'],
  1259: ['range from', 'a range of', 'in range'],
  1260: ['rank among', 'first rank'],
  1261: ['rapid change', 'rapid growth'],
  1262: ['rare animal', 'rarely seen'],
  1263: ['rate of', 'at any rate', 'birth rate'],
  1264: ['rather than', 'would rather', 'or rather'],
  1265: ['reach out', 'reach for', 'reach a goal'],
  1266: ['react to', 'reaction to'],
  1267: ['read aloud', 'read about', 'read through'],
  1268: ['be ready for', 'get ready to'],
  1269: ['real life', 'real name', 'for real'],
  1270: ['realize that', 'come to realize'],
  1271: ['really good', 'not really'],
  1272: ['reason for', 'by reason of', 'for some reason'],
  1273: ['receive sth', 'receive a letter'],
  1274: ['recent news', 'in recent years'],
  1275: ['recipe for', 'a recipe book'],
  1276: ['recognize sb', 'beyond recognition'],
  1277: ['recommend sb to', 'recommend sth for'],
  1278: ['record holder', 'break a record', 'keep a record'],
  1279: ['recover from', 'make a recovery'],
  1280: ['red apple', 'in red', 'see red'],
  1281: ['reduce by', 'reduce to', 'reduce cost'],
  1282: ['refer to', 'reference book'],
  1283: ['reflect on', 'reflection of'],
  1284: ['reform and opening', 'education reform'],
  1285: ['refresh oneself', 'refreshing drink'],
  1286: ['refuse to', 'refuse sth'],
  1287: ['regard as', 'with regard to', 'in this regard'],
  1288: ['region of', 'in the region'],
  1289: ['register for', 'registration form'],
  1290: ['regret doing', 'regret to say'],
  1291: ['regular customer', 'on a regular basis'],
  1292: ['reject sth', 'reject an offer'],
  1293: ['relate to', 'be related to', 'relation ship'],
  1294: ['relax oneself', 'relax by doing'],
  1295: ['release from', 'press release'],
  1296: ['rely on', 'rely upon'],
  1297: ['remain silent', 'remain to be seen'],
  1298: ['remember to', 'remember doing', 'as far as I remember'],
  1299: ['remind sb of', 'remind sb to do'],
  1300: ['remove from', 'remove obstacles'],
  1301: ['rent a house', 'for rent', 'rent out'],
  1302: ['repair shop', 'under repair'],
  1303: ['repeat after', 'repeat that'],
  1304: ['replace sth with', 'replace sb'],
  1305: ['reply to', 'in reply to', 'make a reply'],
  1306: ['report to', 'report on', 'make a report'],
  1307: ['reporter of', 'news reporter'],
  1308: ['represent sb', 'represent sth'],
  1309: ['republic of', 'People\'s Republic'],
  1310: ['require sth', 'require sb to do'],
  1311: ['research on', 'do research', 'research center'],
  1312: ['resist doing', 'resistance to'],
  1313: ['take responsibility for', 'have a sense of responsibility'],
  1314: ['rest area', 'take a rest', 'have a rest'],
  1315: ['a restaurant', 'restaurant owner'],
  1316: ['as a result', 'result in', 'result from'],
  1317: ['return to', 'in return', 'return sth to sb'],
  1318: ['review sth', 'book review', 'under review'],
  1319: ['rice noodle', 'a bowl of rice', 'rice cooker'],
  1320: ['rich in', 'get rich', 'the rich'],
  1321: ['ride a bike', 'ride a horse', 'go for a ride'],
  1322: ['right away', 'right now', 'on the right'],
  1323: ['ring road', 'ring up', 'ring the bell'],
  1324: ['rise up', 'rise to one\'s feet', 'sun rise'],
  1325: ['take a risk', 'at risk', 'risk doing'],
  1326: ['river bank', 'by the river', 'across the river'],
  1327: ['road map', 'road side', 'by road'],
  1328: ['rob sb of', 'rob a bank'],
  1329: ['rock music', 'rock and roll', 'as solid as a rock'],
  1330: ['rocket science', 'launch a rocket'],
  1331: ['role play', 'play a role in', 'role model'],
  1332: ['Roman', 'Roman Empire'],
  1333: ['room number', 'make room for', 'room mate'],
  1334: ['rope in', 'at the end of one\'s rope'],
  1335: ['rose garden', 'a bunch of roses'],
  1336: ['round and round', 'all round', 'go round'],
  1337: ['a row of', 'in a row', 'row a boat'],
  1338: ['rubber band', 'rubber tree'],
  1339: ['rubbish bin', 'rubbish dump', 'take out the rubbish'],
  1340: ['be rude to', 'rude behavior'],
  1341: ['a rule of', 'break the rules', 'as a rule'],
  1342: ['run away', 'run out of', 'run after', 'in the long run'],
  1343: ['rush hour', 'rush to', 'gold rush'],
  // S
  1344: ['be sad about', 'sad news'],
  1345: ['safe and sound', 'be safe to', 'safety first'],
  1346: ['sail boat', 'set sail', 'sail across'],
  1347: ['salad dressing', 'green salad'],
  1348: ['salary increase', 'monthly salary'],
  1349: ['sell sth', 'sell out', 'sell well', 'best seller'],
  1350: ['send a letter', 'send for', 'send out'],
  1351: ['sense of humor', 'sense of direction', 'make sense'],
  1352: ['a series of', 'TV series', 'in series'],
  1353: ['be serious about', 'serious problem', 'take seriously'],
  1354: ['serve sb', 'serve as', 'first serve'],
  1355: ['set up', 'set off', 'set out', 'a set of'],
  1356: ['settle down', 'settle in', 'settle a problem'],
  1357: ['table salt', 'salty food'],
  1358: ['same as', 'the same', 'all the same'],
  1359: ['sand storm', 'on the sand', 'a grain of sand'],
  1360: ['sandwich', 'a sandwich'],
  1361: ['satellite TV', 'launch a satellite'],
  1362: ['Saturday', 'on Saturday', 'Saturday night'],
  1363: ['save money', 'save time', 'save sb from'],
  1364: ['say hello', 'say goodbye', 'that is to say', 'needless to say'],
  1365: ['scared of', 'be scared to', 'scared stiff'],
  1366: ['scarf', 'wear a scarf'],
  1367: ['scene of', 'on the scene', 'behind the scenes'],
  1368: ['at school', 'school bus', 'after school', 'school life'],
  1369: ['science fiction', 'science and technology', 'do science'],
  1370: ['a score of', 'score a goal', 'keep score'],
  1371: ['screen', 'on screen', 'computer screen'],
  1372: ['sea food', 'by sea', 'at sea', 'sea level'],
  1373: ['search for', 'in search of', 'search engine'],
  1374: ['season ticket', 'in season', 'out of season'],
  1375: ['be seated', 'take a seat', 'seat belt'],
  1376: ['second hand', 'in a second', 'wait a second', 'second to none'],
  1377: ['be secret', 'in secret', 'keep a secret'],
  1378: ['secretary of', 'a secretary'],
  1379: ['a section of', 'section A'],
  1380: ['be secure', 'feel secure'],
  1381: ['see off', 'see to', 'as far as I can see', 'let me see'],
  1382: ['seem to', 'it seems that'],
  1383: ['seize the chance', 'seize sb'],
  1384: ['seldom', 'not seldom'],
  1385: ['select from', 'selection of'],
  1386: ['sell out', 'sell well', 'best seller'],
  1387: ['send a message', 'send for', 'send out'],
  1388: ['a sense of', 'make sense', 'in a sense'],
  1389: ['be sensitive to', 'sensitive issue'],
  1390: ['a sentence of', 'make a sentence', 'sentence sb to'],
  1391: ['in September', 'September 1st'],
  1392: ['a series of', 'TV series'],
  1393: ['be serious about', 'serious illness'],
  1394: ['serve as', 'serve sb', 'first come first served'],
  1395: ['set up', 'set off', 'set out', 'a set of'],
  1396: ['settle down', 'settle a dispute'],
  1397: ['seven out of ten', 'at seven'],
  1398: ['a few of', 'several times', 'several of'],
  1399: ['shake hands', 'shake one\'s head', 'shake with fear'],
  1400: ['shall we', 'shall I'],
  1401: ['shame on you', 'what a shame', 'feel ashamed'],
  1402: ['shape of', 'in good shape', 'out of shape'],
  1403: ['share sth with', 'share in', 'market share'],
  1404: ['a shark', 'shark attack'],
  1405: ['sharp knife', 'sharp eyes', '7 o\'clock sharp'],
  1406: ['shave off', 'shave one\'s legs'],
  1407: ['sheep', 'a flock of sheep', 'black sheep'],
  1408: ['sheet of paper', 'a bed sheet'],
  1409: ['shelf', 'on the shelf', 'book shelf'],
  1410: ['shell', 'sea shell', 'shell fish'],
  1411: ['protect sb from', 'take shelter', 'shelter from'],
  1412: ['shine brightly', 'shine shoes'],
  1413: ['a ship of', 'by ship', 'on board a ship'],
  1414: ['a shirt and tie', 'T-shirt'],
  1415: ['be shocked at', 'be shocked to'],
  1416: ['a pair of shoes', 'in sb\'s shoes', 'shoe maker'],
  1417: ['shoot at', 'shoot a movie', 'shoot a goal'],
  1418: ['a gift shop', 'shop keeper', 'go shopping'],
  1419: ['shore', 'on shore', 'off shore'],
  1420: ['be short of', 'in short', 'short cut', 'for short'],
  1421: ['should have done', 'should not'],
  1422: ['shoulder to shoulder', 'shrug one\'s shoulders'],
  1423: ['shout at', 'shout to', 'shout out'],
  1424: ['show around', 'show off', 'show up', 'on show'],
  1425: ['take a shower', 'shower room'],
  1426: ['shut up', 'shut down', 'shut the door'],
  1427: ['shy away', 'be shy with'],
  1428: ['be sick of', 'sick leave', 'fall sick'],
  1429: ['on the side', 'side by side', 'side effect'],
  1430: ['sidewalk', 'on the sidewalk'],
  1431: ['sigh deeply', 'with a sigh'],
  1432: ['sight seeing', 'in sight', 'out of sight', 'catch sight of'],
  1433: ['sign language', 'sign up', 'sign a contract'],
  1434: ['be silent', 'keep silent', 'in silence'],
  1435: ['silk road', 'silk worm', 'silk shirt'],
  1436: ['silly mistake', 'don\'t be silly'],
  1437: ['silver medal', 'silver spoon'],
  1438: ['be similar to', 'similar to', 'similarity between'],
  1439: ['be simple', 'in simple words', 'simply put'],
  1440: ['since then', 'ever since', 'long since'],
  1441: ['sing a song', 'sing along'],
  1442: ['single room', 'single out', 'remain single'],
  1443: ['sink in', 'sink down', 'kitchen sink'],
  1444: ['sir', 'dear Sir'],
  1445: ['sister in law', 'elder sister', 'younger sister'],
  1446: ['sit down', 'sit up', 'sit for', 'sitting room'],
  1447: ['a site of', 'web site', 'building site'],
  1448: ['a size of', 'size up', 'life size'],
  1449: ['skate board', 'go skating', 'ice skate'],
  1450: ['ski resort', 'go skiing'],
  1451: ['be skillful at', 'skillful worker'],
  1452: ['skin care', 'skin deep', 'dry skin'],
  1453: ['a skirt of', 'miniskirt'],
  1454: ['the sky', 'in the sky', 'sky blue'],
  1455: ['go to sleep', 'fall asleep', 'get to sleep'],
  1456: ['be sleepy', 'feel sleepy'],
  1457: ['slice of', 'a slice of bread'],
  1458: ['slide down', 'slide show'],
  1459: ['slight difference', 'not slight'],
  1460: ['be slow at', 'slow down', 'slow motion'],
  1461: ['be small', 'small change', 'feel small'],
  1462: ['be smart', 'smart phone', 'street smart'],
  1463: ['smell of', 'smell good', 'sweet smell'],
  1464: ['smile at', 'with a smile', 'smile on sb'],
  1465: ['smoke free', 'give up smoking', 'smoke alarm'],
  1466: ['smooth surface', 'smoothly', 'in a smooth way'],
  1467: ['a snake', 'snake bite'],
  1468: ['be snowing', 'heavy snow', 'snow man'],
  1469: ['so am I', 'so that', 'so as to', 'or so'],
  1470: ['soap', 'a bar of soap', 'soap opera'],
  1471: ['be social', 'social media', 'social network'],
  1472: ['socialist', 'socialist country'],
  1473: ['soft drink', 'soft ware', 'soft hearted'],
  1474: ['soft ball', 'software', 'hardware'],
  1475: ['soil', 'in the soil', 'rich soil'],
  1476: ['soldier', 'front line soldier'],
  1477: ['solid food', 'on solid ground'],
  1478: ['find a solution', 'solution to'],
  1479: ['solve a problem', 'solve the mystery'],
  1480: ['some of', 'some more', 'some day'],
  1481: ['somebody else', 'or somebody'],
  1482: ['something else', 'something to do', 'have something to do with'],
  1483: ['sometimes', 'sometimes...sometimes'],
  1484: ['somewhere', 'or somewhere', 'somewhere near'],
  1485: ['son and daughter', 'the eldest son'],
  1486: ['song writer', 'sing a song', 'pop song'],
  1487: ['soon after', 'as soon as', 'sooner or later'],
  1488: ['be sorry for', 'sorry to hear', 'feel sorry'],
  1489: ['sort of', 'sort out', 'all sorts of'],
  1490: ['sound like', 'sound good', 'by the sound of it'],
  1491: ['a source of', 'source from'],
  1492: ['South Africa', 'in the south', 'south of'],
  1493: ['a space of', 'in space', 'space ship'],
  1494: ['spare time', 'spare no effort', 'spare tire'],
  1495: ['speak English', 'speak up', 'speak out', 'generally speaking'],
  1496: ['special offer', 'special price', 'nothing special'],
  1497: ['a speech on', 'make a speech', 'free speech'],
  1498: ['speed up', 'at full speed', 'speed limit'],
  1499: ['spell out', 'spell checker'],
  1500: ['spend time on', 'spend money on', 'spend...doing'],
  1501: ['spider web', 'spider man'],
  1502: ['spirit of', 'in high spirits', 'team spirit'],
  1503: ['a spoon of', 'soup spoon', 'tea spoon'],
  1504: ['sport meeting', 'do sports', 'sportswear'],
  1505: ['spread out', 'spread to', 'spread the news'],
  1506: ['spring break', 'spring festival', 'in spring'],
  1507: ['square', 'in the square', 'Times Square'],
  1508: ['stable', 'in a stable condition'],
  1509: ['staff room', 'staff member', 'teaching staff'],
  1510: ['stage of', 'on stage', 'go on stage'],
  1511: ['stair case', 'up stairs', 'down stairs'],
  1512: ['be strange to', 'strange to say'],
  1513: ['a stranger to', 'stranger danger'],
  1514: ['strawberry', 'strawberry jam'],
  1515: ['stream of', 'down stream', 'up stream'],
  1516: ['street', 'in the street', 'street food', 'down the street'],
  1517: ['strength of', 'with all one\'s strength'],
  1518: ['be stressed out', 'under stress'],
  1519: ['strict with', 'be strict about'],
  1520: ['strike a match', 'on strike', 'go on strike'],
  1521: ['be strong enough', 'strong wind'],
  1522: ['a student of', 'student union', 'student ID'],
  1523: ['study for', 'study hard', 'study abroad'],
  1524: ['be stupid', 'stupid mistake'],
  1525: ['subject of', 'change the subject', 'school subject'],
  1526: ['be successful in', 'a great success'],
  1527: ['such as', 'such...that', 'no such thing'],
  1528: ['suck in', 'suck up'],
  1529: ['sudden death', 'all of a sudden'],
  1530: ['suffer from', 'suffer loss'],
  1531: ['sugar free', 'a spoon of sugar', 'blood sugar'],
  1532: ['suggest that', 'suggest doing', 'make a suggestion'],
  1533: ['suit case', 'suit sb', 'bathing suit'],
  1534: ['summer holiday', 'in summer', 'summer camp'],
  1535: ['Sunday', 'on Sunday', 'Sunday morning'],
  1536: ['sun glasses', 'in the sun', 'sun shine', 'sun bath'],
  1537: ['supermarket', 'go to the supermarket'],
  1538: ['a supplement to', 'dietary supplement'],
  1539: ['supply of', 'supply and demand', 'in supply'],
  1540: ['be supposed to', 'not supposed to'],
  1541: ['be sure to', 'make sure', 'for sure'],
  1542: ['surf the net', 'surf board', 'web surfing'],
  1543: ['be surprised at', 'to one\'s surprise', 'in surprise'],
  1544: ['a survey on', 'conduct a survey'],
  1545: ['survive from', 'survival of', 'survival skills'],
  1546: ['suspect sb of', 'a suspect of'],
  1547: ['swallow up', 'swallow hard'],
  1548: ['swap sth for', 'do a swap'],
  1549: ['sweat shirt', 'sweat heavily'],
  1550: ['a sweater', 'wool sweater'],
  1551: ['sweep the floor', 'sweep away'],
  1552: ['sweet dream', 'sweet and sour', 'have a sweet tooth'],
  1553: ['swim ming pool', 'go swimming', 'swim suit'],
  1554: ['swing', 'on a swing', 'swing door'],
  1555: ['switch on', 'switch off', 'switch to'],
  // T
  1556: ['table tennis', 'at the table', 'time table'],
  1557: ['tail of', 'tail end'],
  1558: ['take care of', 'take place', 'take part in', 'take it easy'],
  1559: ['a tale of', 'tell a tale', 'fairy tale'],
  1560: ['talent show', 'have a talent for'],
  1561: ['talk about', 'talk to', 'talk over', 'small talk'],
  1562: ['be tall', 'tall and thin'],
  1563: ['taste good', 'taste like', 'have a taste'],
  1564: ['taxi driver', 'take a taxi', 'by taxi'],
  1565: ['tea pot', 'a cup of tea', 'green tea', 'black tea'],
  1566: ['teach sb sth', 'teach oneself', 'teaching method'],
  1567: ['a team of', 'team work', 'team member'],
  1568: ['be in tears', 'burst into tears', 'move to tears'],
  1569: ['a piece of technology', 'technology development'],
  1570: ['phone call', 'make a call', 'on the phone'],
  1571: ['a television', 'on TV', 'watch TV'],
  1572: ['tell sb sth', 'tell a lie', 'tell the truth', 'tell apart'],
  1573: ['a temperature of', 'have a temperature', 'take one\'s temperature'],
  1574: ['tennis court', 'play tennis', 'table tennis'],
  1575: ['be tense', 'tense up'],
  1576: ['a term of', 'in terms of', 'long term'],
  1577: ['be terrible', 'terrible weather'],
  1578: ['a test of', 'take a test', 'pass the test', 'fail the test'],
  1579: ['text book', 'text message', 'full text'],
  1580: ['than usual', 'rather than', 'other than'],
  1581: ['thank sb for', 'thanks to', 'thank you'],
  1582: ['that is', 'that is to say', 'so that'],
  1583: ['theatre', 'go to the theatre', 'movie theatre'],
  1584: ['then and there', 'now and then', 'since then'],
  1585: ['theory of', 'in theory'],
  1586: ['there be', 'over there', 'here and there'],
  1587: ['therefore', 'and therefore'],
  1588: ['be thick', 'thick fog', 'thick soup'],
  1589: ['be thin', 'thin and thick', 'thin air'],
  1590: ['think about', 'think of', 'think over', 'think twice'],
  1591: ['be thirsty for', 'feel thirsty'],
  1592: ['thirty', 'in one\'s thirties'],
  1593: ['thorough', 'be thorough'],
  1594: ['though', 'even though', 'as though'],
  1595: ['a thought of', 'on second thought', 'deep in thought'],
  1596: ['thousand', 'thousands of', 'one thousand'],
  1597: ['thread', 'thread a needle', 'a thread of'],
  1598: ['be through with', 'go through', 'look through'],
  1599: ['throw away', 'throw at', 'throw up'],
  1600: ['Thursday', 'on Thursday', 'Thursday evening'],
  1601: ['ticket office', 'a ticket to', 'one way ticket'],
  1602: ['be tidy', 'tidy up', 'tidy room'],
  1603: ['tie up', 'tie the shoe', 'neck tie'],
  1604: ['tiger', 'paper tiger', 'as fierce as a tiger'],
  1605: ['be tight', 'tight schedule', 'in a tight spot'],
  1606: ['time table', 'on time', 'in time', 'all the time'],
  1607: ['tiny', 'a tiny bit', 'tiny amount'],
  1608: ['be tired of', 'be tired from', 'feel tired'],
  1609: ['title of', 'book title', 'under the title of'],
  1610: ['to one\'s surprise', 'to begin with', 'to some extent'],
  1611: ['toast', 'make toast', 'propose a toast'],
  1612: ['today', 'today\'s news', 'today and tomorrow'],
  1613: ['toe', 'from top to toe', 'toe nail'],
  1614: ['together with', 'get together', 'togetherness'],
  1615: ['a toilet', 'toilet paper', 'public toilet'],
  1616: ['tomato', 'tomato sauce', 'tomato juice'],
  1617: ['tomorrow', 'tomorrow morning', 'the day after tomorrow'],
  1618: ['tone of voice', 'tone up', 'tone down'],
  1619: ['tongue', 'mother tongue', 'hold one\'s tongue'],
  1620: ['too...to', 'too much', 'too many', 'me too'],
  1621: ['a tool for', 'tool box', 'use a tool'],
  1622: ['tooth ache', 'brush one\'s teeth', 'tooth paste'],
  1623: ['top of', 'on top of', 'at the top of'],
  1624: ['topic of', 'off topic', 'change the topic'],
  1625: ['total of', 'in total', 'a total of'],
  1626: ['touch down', 'get in touch', 'keep in touch', 'lose touch'],
  1627: ['tour guide', 'on tour', 'a tour of'],
  1628: ['toward', 'toward the end'],
  1629: ['towel', 'paper towel', 'bath towel'],
  1630: ['a tower of', 'tower block', 'Eiffel Tower'],
  1631: ['a town of', 'in town', 'town center', 'down town'],
  1632: ['toy shop', 'a toy for', 'play with toys'],
  1633: ['trace of', 'trace back', 'without a trace'],
  1634: ['track and field', 'on the right track', 'lose track of'],
  1635: ['trade with', 'international trade', 'free trade'],
  1636: ['tradition al', 'traditional food', 'by tradition'],
  1637: ['traffic jam', 'traffic light', 'heavy traffic'],
  1638: ['be trained', 'train station', 'by train', 'catch a train'],
  1639: ['translate into', 'translation of'],
  1640: ['transport system', 'public transport'],
  1641: ['travel agency', 'travel around', 'time travel'],
  1642: ['treasure', 'treasure hunt', 'national treasure'],
  1643: ['treat sb to', 'treat as', 'it\'s my treat'],
  1644: ['a tree of', 'tree top', 'family tree'],
  1645: ['a trend of', 'trend toward'],
  1646: ['trial', 'on trial', 'trial and error'],
  1647: ['trick or treat', 'play a trick on'],
  1648: ['a trip to', 'business trip', 'field trip'],
  1649: ['triumph', 'in triumph'],
  1650: ['trolley', 'shopping trolley', 'trolley bus'],
  1651: ['trophy', 'win a trophy'],
  1652: ['trouble maker', 'in trouble', 'have trouble doing', 'get into trouble'],
  1653: ['trousers', 'a pair of trousers'],
  1654: ['truck driver', 'by truck'],
  1655: ['come true', 'true or false', 'a true story'],
  1656: ['trust in', 'trust sb', 'build trust'],
  1657: ['tell the truth', 'in truth', 'truthful'],
  1658: ['try to', 'try on', 'try out', 'try one\'s best'],
  1659: ['a T-shirt', 'wear a T-shirt'],
  1660: ['Tuesday', 'on Tuesday', 'Tuesday afternoon'],
  1661: ['a tunnel through', 'in a tunnel'],
  1662: ['turkey', 'roast turkey'],
  1663: ['turn on', 'turn off', 'turn down', 'turn up', 'in turn'],
  1664: ['TV set', 'watch TV', 'on TV', 'TV program'],
  1665: ['twelve', 'at twelve', 'twelve o\'clock'],
  1666: ['twenty', 'in one\'s twenties', 'twenty first'],
  1667: ['twice', 'twice a week', 'think twice'],
  1668: ['twin brother', 'twin sister', 'identical twins'],
  1669: ['twist', 'twist around', 'plot twist'],
  1670: ['two', 'the two of', 'in twos'],
  1671: ['a type of', 'blood type', 'all types of'],
  1672: ['typhoon', 'typhoon warning'],
  1673: ['typical of', 'it\'s typical that'],
  // U
  1674: ['be ugly', 'ugly duckling'],
  1675: ['an umbrella', 'under an umbrella'],
  1676: ['be under', 'under way', 'under ground'],
  1677: ['understand sth', 'make oneself understood', 'understanding of'],
  1678: ['as usual', 'than usual'],
  1679: ['up and down', 'up to', 'up to now'],
  1680: ['be used to', 'used to do', 'get used to'],
  1681: ['be useful for', 'useful to'],
  1682: ['be upset about', 'upset stomach'],
  1683: ['be in use', 'out of use', 'make use of'],
  1684: ['usually', 'more than usual'],
  1685: ['vacuum', 'vacuum cleaner', 'in a vacuum'],
  1686: ['be valid', 'valid reason', 'no longer valid'],
  1687: ['a valley of', 'in the valley'],
  1688: ['be valuable', 'valuable experience'],
  1689: ['a variety of', 'variety show'],
  1690: ['various of', 'for various reasons'],
  1691: ['a vast of', 'vast area'],
  1692: ['VCD', 'play a VCD'],
  1693: ['a vegetable', 'vegetable soup', 'green vegetables'],
  1694: ['very good', 'very much', 'very well'],
  1695: ['be victor', 'victory over'],
  1696: ['a video of', 'video game', 'video camera'],
  1697: ['a view of', 'in view of', 'point of view'],
  1698: ['a village of', 'in the village', 'village life'],
  1699: ['be violent', 'violent crime'],
  1700: ['violin', 'play the violin'],
  1701: ['visit sb', 'pay a visit to', 'on a visit'],
  1702: ['a visitor from', 'visitors\' book'],
  1703: ['warm up', 'keep warm'],
  1704: ['voice', 'in a low voice', 'raise one\'s voice', 'at the top of one\'s voice'],
  1705: ['volleyball', 'play volleyball', 'volleyball court'],
  1706: ['volume of', 'turn up the volume', 'speak volume'],
  // W
  1707: ['wait for', 'wait on', 'can\'t wait to'],
  1708: ['a waiter in', 'head waiter'],
  1709: ['wake up', 'wake sb up', 'wide awake'],
  1710: ['walk away', 'walk through', 'go for a walk', 'walk dog'],
  1711: ['wall paper', 'on the wall', 'Great Wall'],
  1712: ['wallet', 'in one\'s wallet', 'lose one\'s wallet'],
  1713: ['want to', 'want sth', 'in want of'],
  1714: ['be at war', 'go to war', 'civil war'],
  1715: ['be warm', 'warm up', 'keep warm'],
  1716: ['warn sb of', 'warn sb against', 'warn sb not to'],
  1717: ['wash up', 'wash one\'s face', 'wash machine'],
  1718: ['waste time', 'waste of money', 'don\'t waste'],
  1719: ['watch TV', 'watch out', 'keep watch', 'on watch'],
  1720: ['water fall', 'fresh water', 'water melon', 'drink water'],
  1721: ['a wave of', 'wave to sb', 'make waves'],
  1722: ['a way of', 'by the way', 'on the way', 'in a way'],
  1723: ['we are', 'we will'],
  1724: ['be weak in', 'weak point'],
  1725: ['be wealthy', 'a wealth of', 'national wealth'],
  1726: ['wear out', 'wear a coat', 'casual wear'],
  1727: ['weather forecast', 'fine weather', 'bad weather'],
  1728: ['weave', 'weave a story', 'weave through'],
  1729: ['web site', 'web page', 'surf the web'],
  1730: ['wedding ceremony', 'wedding dress', 'at a wedding'],
  1731: ['whether or not', 'whether...or'],
  1732: ['which one', 'which of'],
  1733: ['while away', 'after a while', 'in a while', 'once in a while'],
  1734: ['whisper to', 'in a whisper'],
  1735: ['whistle', 'blow a whistle', 'whistle blow'],
  1736: ['white collar', 'white snow', 'in white'],
  1737: ['who is', 'who else'],
  1738: ['whole day', 'on the whole', 'a whole lot'],
  1739: ['whose', 'whose book'],
  1740: ['why not', 'that\'s why', 'why don\'t you'],
  1741: ['be wide', 'wide open', 'far and wide'],
  1742: ['be a wife', 'husband and wife', 'house wife'],
  1743: ['be wild', 'wild animal', 'in the wild'],
  1744: ['will be', 'will have done'],
  1745: ['be willing to', 'willing to help'],
  1746: ['win a prize', 'win the game', 'win over'],
  1747: ['wind up', 'wind blow', 'strong wind'],
  1748: ['a window of', 'by the window', 'window shopping'],
  1749: ['be windy', 'windy day'],
  1750: ['wine glass', 'red wine', 'a bottle of wine'],
  1751: ['wing of', 'on the wing', 'take under one\'s wing'],
  1752: ['winner of', 'award winner'],
  1753: ['winter holiday', 'in winter', 'winter vacation'],
  1754: ['wipe out', 'wipe off', 'wipe one\'s face'],
  1755: ['be wise to', 'wise man', 'wise choice'],
  1756: ['wish to', 'wish sb sth', 'make a wish', 'best wishes'],
  1757: ['be with', 'go with', 'together with'],
  1758: ['within', 'within reach', 'within limits'],
  1759: ['without', 'without doubt', 'do without', 'go without'],
  1760: ['a wolf', 'cry wolf', 'wolf down'],
  1761: ['a woman of', 'woman and man', 'business woman'],
  1762: ['be surprised at', 'wonder about', 'no wonder'],
  1763: ['wooden', 'a piece of wood', 'in the woods', 'fire wood'],
  1764: ['a wool of', 'wool sweater', 'pull the wool over'],
  1765: ['word by word', 'in other words', 'keep one\'s word'],
  1766: ['at work', 'out of work', 'work hard', 'work out'],
  1767: ['a worker of', 'worker and peasant'],
  1768: ['world wide', 'in the world', 'all over the world'],
  1769: ['be worried about', 'worry about', 'don\'t worry'],
  1770: ['be worth', 'worth doing', 'well worth'],
  1771: ['would like', 'would rather', 'would have'],
  1772: ['a wound of', 'be wounded', 'wound healing'],
  1773: ['wrap up', 'wrap sth in', 'under wraps'],
  1774: ['write down', 'write to', 'write back'],
  1775: ['be wrong', 'go wrong', 'wrong number'],
  1776: ['the wrong way', 'get wrong'],
  // X
  1777: ['X-ray', 'take an X-ray'],
  // Y
  1778: ['yard', 'in the yard', 'back yard'],
  1779: ['year by year', 'year after year', 'last year', 'new year'],
  1780: ['be yellow', 'turn yellow'],
  1781: ['yes or no', 'say yes to'],
  1782: ['yesterday', 'yesterday morning', 'the day before yesterday'],
  1783: ['not yet', 'already yet', 'as yet'],
  1784: ['be young', 'young and old', 'young people'],
  // Z
  1785: ['in the zoo', 'zoo keeper'],
};

let changed = 0;
let notFound = [];

for (const line of fs.readFileSync('E:\\Tina\\自研背单词软件\\empty_colllocations.txt', 'utf-8').split('
').filter(l => l.trim())) {
  const parts = line.trim().split('|');
  if (parts.length < 4) continue;
  const num = parseInt(parts[0]);
  
  const wordObj = data.find(w => w.number === num);
  if (!wordObj) continue;
  if (wordObj.collocations && wordObj.collocations.length > 0) continue;
  
  if (collMap[num]) {
    wordObj.collocations = collMap[num];
    changed++;
  } else {
    notFound.push(num + ' ' + wordObj.word);
  }
}

fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf-8');
console.log('Total fixed: ' + changed + ' words with empty collocations');
if (notFound.length > 0) {
  console.log('Not found in map (' + notFound.length + '):');
  notFound.forEach(n => console.log('  ' + n));
}
console.log('Done.');
